src/objects/AccountPromotionMember__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>AccountPromotionMembers</relationshipLabel>
        <relationshipName>AccountPromotionMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AccountPromotionMember</label>
    <nameField>
        <label>AccountPromotionMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountPromotionMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Businessprocess__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>Businessprocess</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businessprocesss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BusinessProcessParameter__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>BusinessProcessParameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessProcessParameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrganizationAccountMember__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>OrganizationAccountMembers</relationshipLabel>
        <relationshipName>OrganizationAccountMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OrganizationAccountMember</label>
    <nameField>
        <label>OrganizationAccountMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrganizationAccountMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrganizationPromotionMember__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>OrganizationPromotionMembers</relationshipLabel>
        <relationshipName>OrganizationPromotionMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>OrganizationPromotionMembers</relationshipLabel>
        <relationshipName>OrganizationPromotionMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OrganizationPromotionMember</label>
    <nameField>
        <label>OrganizationPromotionMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrganizationPromotionMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfigType__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>PageConfigType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>

    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>ProductGroup</label>
    <nameField>
        <label>ProductGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroupMember__c.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProductGroup</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>ProductGroupMembers</relationshipLabel>
        <relationshipName>ProductGroupMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProductGroupMember</label>
    <nameField>
        <displayFormat>pgm-{00000000}</displayFormat>
        <label>ProductGroupMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductGroupMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PromotionMember__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>PromotionMembers</relationshipLabel>
        
        <relationshipName>PromotionMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PromotionMember</label>
    <nameField>
        <label>PromotionMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PromotionMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StringCatalogItem__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>StringCatalogItem</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StringCatalogItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttribute__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlAttribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttributeGroup__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlAttributeGroup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributeGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttributeType__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlAttributeType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributeType</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlGroup__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlGroup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlType__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CleanupTestData.cls
/*
 @Company: YOUR SL
 @Author: KVE
 @Creation date: 14 /06/ 2015
 @Ref: Create dashboard for editing app settings
*/
public with sharing class CleanupTestData {

    public static void run(boolean defaultValue) {
        //Deleting stringCatalogItems
        List<StringCatalogItem__c> stringCatalogItemsList = [SELECT Id
                                                        FROM StringCatalogItem__c
                                                        WHERE IsDefault__c != : defaultValue];
        if (!stringCatalogItemsList.isEmpty()) {
            delete  stringCatalogItemsList;
            System.debug('stringCatalogItemsList -->' + stringCatalogItemsList.size());
        }
        
        //Deleting uiControlAttribute
        List<UIControlAttribute__c> uiControlAttribute = [SELECT Id
                                                        FROM UIControlAttribute__c
                                                        WHERE IsDefault__c != : defaultValue];
        if (!uiControlAttribute.isEmpty()) {
            delete  uiControlAttribute;
            System.debug('uiControlAttribute -->' + uiControlAttribute.size());
        }
        //Deleting uiControlAttributeType
        List<UIControlAttributeType__c> uiControlAttributeType = [SELECT Id
                                                                    FROM UIControlAttributeType__c
                                                                    WHERE IsDefault__c != : defaultValue];
        if (!uiControlAttributeType.isEmpty()) {
            delete  uiControlAttributeType;
            System.debug('uiControlAttributeType -->' + uiControlAttributeType.size());
        }

        //Deleting uiControlAttributeGroup
        List<UIControlAttributeGroup__c> uiControlAttributeGroup = [SELECT Id
                                                                    FROM UIControlAttributeGroup__c
                                                                    WHERE IsDefault__c != : defaultValue];
        if (!uiControlAttributeGroup.isEmpty()) {
            delete  uiControlAttributeGroup;
            System.debug('uiControlAttributeGroup -->' + uiControlAttributeGroup.size());
        }

        //Deleting uiControl
        List<UIControl__c> uiControl = [SELECT Id
                                        FROM UIControl__c
                                        WHERE IsDefault__c != : defaultValue];
        if (!uiControl.isEmpty()) {
            delete  uiControl;
            System.debug('uiControl -->' + uiControl.size());
        }

        //Deleting uiControlType
        List<UIControlType__c> uiControlType = [SELECT Id
                                                FROM UIControlType__c
                                                WHERE IsDefault__c != : defaultValue];
        if (!uiControlType.isEmpty()) {
            delete  uiControlType;
            System.debug('uiControlType -->' + uiControlType.size());
        }

        //Deleting uiControlGroup
        List<UIControlGroup__c> uiControlGroup = [SELECT Id
                                                FROM UIControlGroup__c
                                                WHERE IsDefault__c != : defaultValue];
        if (!uiControlGroup.isEmpty()) {
            delete  uiControlGroup;
            System.debug('uiControlGroup -->' + uiControlGroup.size());
        }

        //Deleting pageConfig
        List<PageConfig__c> pageConfig = [SELECT Id
                                          FROM PageConfig__c
                                          WHERE IsDefault__c != : defaultValue];
        if (!pageConfig.isEmpty()) {
            delete  pageConfig;
            System.debug('pageConfig -->' + pageConfig.size());
        }

        //Deleting pageConfigTypes
        List<PageConfigType__c> pageConfigType = [SELECT Id
                                                FROM PageConfigType__c
                                                WHERE IsDefault__c != : defaultValue];
        if (!pageConfigType.isEmpty()) {
            delete  pageConfigType;
            System.debug('pageConfigType -->' + pageConfigType.size());
        }

        //Deleting appSetting
        List<AppSettings__c> appSettings = [SELECT Id
                                            FROM AppSettings__c
                                            WHERE IsDefault__c != : defaultValue];
        if (!appSettings.isEmpty()) {
            delete  appSettings ;
            System.debug('appSettings -->' + appSettings.size());
        }

        //Deleting mobileDevices
        List<MobileDevice__c> mobileDevice = [SELECT Id
                                              FROM MobileDevice__c
                                              WHERE IsDefault__c != : defaultValue];
        if (!mobileDevice.isEmpty()) {
            delete  mobileDevice;
            System.debug('mobileDevice -->' + mobileDevice.size());
        }

        List<Attachment> listAttachment = [SELECT Id
                                              FROM Attachment
                                              ];
        if (!listAttachment.isEmpty()) {
            delete  listAttachment;
            System.debug('mobileDevice -->' + mobileDevice.size());
        }
        
        List<Businessprocess__c> listBusinessprocess = [SELECT Id FROM Businessprocess__c];
        if(!listBusinessprocess.isEmpty()){
            delete listBusinessprocess;
            System.debug('Businessprocess----------------'+listBusinessprocess.size());
        }
        
        List<BusinessProcessParameter__c> listBusinessProcessParameter = [SELECT Id FROM BusinessProcessParameter__c];
        if(!listBusinessProcessParameter.isEmpty()){
            delete listBusinessProcessParameter;
            System.debug('listBusinessProcessParameter----------------'+listBusinessProcessParameter.size());
        }
        
        List<Product2>  listProduct2 = [SELECT Id FROM Product2];       
        if(!listProduct2.isEmpty()){
            delete listProduct2;
            system.debug('listProduct2---------------'+listProduct2.size());
        }
        
        List<ProductGroup__c> listProductGroup = [SELECT Id FROM ProductGroup__c];
        if(!listProductGroup.isEmpty()){
            delete listProductGroup;
            system.debug('listProductGroup---------------------'+listProductGroup.size());
        }
        List<ProductGroupMember__c> listProductGroupMember = [SELECT Id FROM ProductGroupMember__c];
        if(!listProductGroupMember.isEmpty()){
            delete listProductGroupMember;
            system.debug('listProductGroupMember--------------'+listProductGroupMember.size());
        }
        List<Pricebook2> listPriceBook2 = [SELECT Id FROM Pricebook2 WHERE isStandard=false];
        if(!listPriceBook2.isEmpty()){
            delete listPriceBook2;
            system.debug('listPriceBook2-------------'+listPriceBook2.size());
        }
        List<PricebookEntry> listPricebookEntry = [SELECT Id FROM PricebookEntry];
        if(!listPricebookEntry.isEmpty()){
            delete listPricebookEntry;
            system.debug('listPricebookEntry-----------------'+listPricebookEntry.size());
        }
        List<Account> listAccount = [SELECT Id FROM Account where Name NOT IN ('GenePoint','United Oil & Gas, UK','United Oil & Gas, Singapore','Edge Communications','Burlington Textiles Corp of America','Grand Hotels & Resorts Ltd','Express Logistics and Transport','University of Arizona','United Oil & Gas Corp.')];
        if(!listAccount.isEmpty()){
            delete listAccount;
            system.debug('listAccount--------------------'+listAccount.size());
        }
        List<AccountPriceBookMember__c> listAccountPriceBookMember = [SELECT Id FROM AccountPriceBookMember__c];
        if(!listAccountPriceBookMember.isEmpty()){
            delete listAccountPriceBookMember;
            system.debug('listAccountPriceBookMember-----------------'+listAccountPriceBookMember.size());
        }
        
        List<Promotion__c> listPromotion = [SELECT Id FROM Promotion__c];
        if(!listPromotion.isEmpty()){
            delete listPromotion;
            system.debug('listPromotion-----------------'+listPromotion.size());
        }
        List<AccountPromotionMember__c> listAccountPromotionMember = [SELECT Id FROM AccountPromotionMember__c];
        if(!listAccountPromotionMember.isEmpty()){
            delete listAccountPromotionMember;
            system.debug('listAccountPromotionMember--------------'+listAccountPromotionMember.size());
        }
        List<PromotionMember__c> listPromotionMember = [SELECT Id FROM PromotionMember__c];
        if(!listPromotionMember.isEmpty()){
            delete listPromotionMember;
            system.debug('listPromotionMember-------------------'+listPromotionMember.size());
        }
        List<Organization__c> listOrganization = [SELECT Id FROM Organization__c];  
        if(!listOrganization.isEmpty()){
            delete listOrganization;
            system.debug('listOrganization----------------'+listOrganization.size());
        }
        List<OrganizationAccountMember__c> listOrganizationAccountMember = [SELECT Id FROM OrganizationAccountMember__c];
        if(!listOrganizationAccountMember.isEmpty()){
            delete listOrganizationAccountMember;
            system.debug('listOrganizationAccountMember------------------'+listOrganizationAccountMember.size());
        }
        List<OrganizationPriceBookMember__c> listOrganizationPriceBookMember = [SELECT Id FROM OrganizationPriceBookMember__c];
        if(!listOrganizationPriceBookMember.isEmpty()){
            delete listOrganizationPriceBookMember;
            system.debug('listOrganizationPriceBookMember------------------------'+listOrganizationPriceBookMember.size());
        }
        List<OrganizationPromotionMember__c> listOrganizationPromotionMember = [SELECT Id FROM OrganizationPromotionMember__c];
        if(!listOrganizationPromotionMember.isEmpty()){
            delete listOrganizationPromotionMember;
            system.debug('listOrganizationPromotionMember-----------'+listOrganizationPromotionMember.size());
        }
    }
    
    public static void createNeraTriggerCustomSetting(){
        //Inserting NeraTriggerCustomSetting
        List<NeraTriggerCustomSetting__c> listNeraTriggerCustomSetting = new List<NeraTriggerCustomSetting__c>();
        
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'AccountHashKey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'AccountPriceBookMemberHashkey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'AccountPromotionMemberHashkey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'AppsettingPostDeployment', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'BusinessLogic', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'BusinessParameterLogic', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'EventHashKey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'Organization', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'OrganizationAccountMember', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'OrganizationPromotionMemberHashkey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'PageConfig', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'Pricebook2Hashkey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'ProductGroupHashkey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'Product2Hashkey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'PromotionHashkey', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'UIControl', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'UIControlAttribute', IsActive__c = True));
        listNeraTriggerCustomSetting.add( new NeraTriggerCustomSetting__c(Name = 'ValidateOverlapping', IsActive__c = True));
        listNeraTriggerCustomSetting.add(new NeraTriggerCustomSetting__c(Name = 'VisitFrequency', IsActive__c = True));
        listNeraTriggerCustomSetting.add(new NeraTriggerCustomSetting__c(Name = 'OrgPotentialAvailability', IsActive__c = True));
        listNeraTriggerCustomSetting.add(new NeraTriggerCustomSetting__c(Name = 'ValidateStorm', IsActive__c = True));

        insert listNeraTriggerCustomSetting;
    }
}