src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GeoLocations__c</fullName>
        <label>GeoLocations</label>
        <scale>15</scale>
        <type>Location</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Organization__c.object
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrganizationAccountMember__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OrganizationAccountMembers</relationshipLabel>
        <relationshipName>OrganizationAccountMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>OrganizationAccountMembers</relationshipLabel>
        <relationshipName>OrganizationAccountMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OrganizationAccountMember</label>
    <nameField>
        <label>OrganizationAccountMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrganizationAccountMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ctrOrganizationRelatedAccount.cls
public with sharing class ctrOrganizationRelatedAccount {
    public List<Account> listAccount {get; set;}
    public String orgId {get;set;}
    public ctrOrganizationRelatedAccount(ApexPages.StandardController controller) {
        orgId = apexpages.currentpage().getparameters().get('id');
        organizationData();
    }
    public void organizationData() {
        listAccount = new List<Account>();
        for (OrganizationAccountMember__c orgmember : [SELECT Account__c, Account__r.Name, Account__r.OwnerId, Account__r.GeoLocations__c, Organization__c FROM OrganizationAccountMember__c WHERE Organization__c = :orgId]) {
            Account acc = new Account();
            acc.Id = orgmember.Account__c;
            acc.Name = orgmember.Account__r.Name;
            acc.OwnerId = orgmember.Account__r.OwnerId;
            listAccount.add(acc);
        }

    }
}