src/objects/AccountPosMember__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountPosMembers</relationshipLabel>
        <relationshipName>AccountPosMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PageConfig__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfig</label>
        <referenceTo>PageConfig__c</referenceTo>
        <relationshipLabel>AccountPosMembers</relationshipLabel>
        <relationshipName>AccountPosMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AccountPosMember</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountPosMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AuditQuestion__c.object
<CustomObject>
    <fields>
        <fullName>AuditQuestionType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AuditQuestionType</label>
        <referenceTo>AuditQuestionType__c</referenceTo>
        <relationshipLabel>AuditQuestions</relationshipLabel>
        <relationshipName>AuditQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MaximumValue__c</fullName>
        <label>MaximumValue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Potential__c</fullName>
        <label>Potential</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>AuditQuestion</label>
    <nameField>
        <displayFormat>Question-{000}</displayFormat>
        <label>AuditQuestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AuditQuestions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AuditQuestionType__c.object
<CustomObject>
    <fields>
        <fullName>HasWeightage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasWeightage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaximumValue__c</fullName>
        <label>MaximumValue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MultiSelectFields__c</fullName>
        <label>MultiSelectFields</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MultiSelectPredicate__c</fullName>
        <label>MultiSelectPredicate</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MultiSelectSource__c</fullName>
        <label>MultiSelectSource</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <label>Step</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weightage__c</fullName>
        <label>Weightage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AuditQuestionType</label>
    <nameField>
        <label>AuditQuestionType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AuditQuestionTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POIHeader__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UIControl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControl</label>
        <referenceTo>UIControl__c</referenceTo>
        <relationshipName>PosHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>POIHeader</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POIHeaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POIQuestion__c.object
<CustomObject>
    <fields>
        <fullName>AuditQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AuditQuestion</label>
        <referenceTo>AuditQuestion__c</referenceTo>
        <relationshipLabel>POIQuestions</relationshipLabel>
        <relationshipName>POIQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UIControl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControl</label>
        <referenceTo>UIControl__c</referenceTo>
        <relationshipLabel>POIQuestions</relationshipLabel>
        <relationshipName>POIQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>POIQuestion</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POIQuestions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POIType__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HasWeightage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasWeightage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Weightage__c</fullName>
        <label>Weightage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POIType</label>
    <nameField>
        <label>POIType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POIType</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential__c.object
<CustomObject>
    <label>Potential</label>
    <nameField>
        <label>Potential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POIType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POIType</label>
        <referenceTo>POIType__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WsSurveyEcutionDeployment.cls
@RestResource(urlmapping = '/SurveyExecutionDeployment/*')

global class WsSurveyEcutionDeployment implements UcbWs {

	public static UcbWsResponse doReply(UcbWsRequest request) {
        return new UcbWsResponse();
    }
    @HttpGet
    global static void wsGet() {
    	UcbWsRequest myRequest = new UcbWsRequest(RestContext.request);
    	if(myRequest.appSetting == 'AccountPosMember'){ 
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnAccountPosMember()));
        } 
        else if(myRequest.appSetting == 'POIType'){ 
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnPOIType()));
        } 
        else if(myRequest.appSetting == 'POIHeader'){ 
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnPOIHeader()));
        } 
        else if(myRequest.appSetting == 'POIQuestion'){ 
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnPOIQuestion()));
        }
        else if(myRequest.appSetting == 'AuditQuestion'){ 
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnAuditQuestion()));
        }
        else if(myRequest.appSetting == 'AuditQuestionType'){ 
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnAuditQuestionType()));
        }
        
        RestContext.response.addHeader('Content-Type', 'application/json');
    }
    public static List<AccountPosMember__c> returnAccountPosMember(){
    	List<AccountPosMember__c> listAccPosMember = new List<AccountPosMember__c>();
    		listAccPosMember = [SELECT Name,Account__c,PageConfig__c FROM AccountPosMember__c LIMIT 50000];
		return listAccPosMember;
    }

    public static List<POIType__c> returnPOIType(){
    	List<POIType__c> listPoiType = new List<POIType__c>();
    	listPoiType = [SELECT Name,AttachmentId__c,HasWeightage__c,Order__c,Weightage__c FROM POIType__c LIMIT 50000];
    	return listPoiType;
    }

    public static List<POIHeader__c> returnPOIHeader(){
    	List<POIHeader__c> listPOIHeader = new List<POIHeader__c>();
    	listPOIHeader = [SELECT Name,AttachmentId__c,Description__c,UIControl__c FROM POIHeader__c LIMIT 50000];
    	return listPOIHeader;
    }

    public static List<POIQuestion__c> returnPOIQuestion(){
    	List<POIQuestion__c> listPOIQuestion = new List<POIQuestion__c>();
    	listPOIQuestion = [SELECT Name,AuditQuestion__c,UIControl__c FROM POIQuestion__c LIMIT 50000];
    	return listPOIQuestion;
    }

    public static List<AuditQuestion__c> returnAuditQuestion(){
    	List<AuditQuestion__c> listAuditQuestion = new List<AuditQuestion__c>();
    	listAuditQuestion = [SELECT Name,AuditQuestionType__c,Description__c,Potential__c FROM AuditQuestion__c LIMIT 50000];
    	return listAuditQuestion;
    }

    public static List<AuditQuestionType__c> returnAuditQuestionType(){
    	List<AuditQuestionType__c> listAuditQuestionType = new List<AuditQuestionType__c>();
    	listAuditQuestionType = [SELECT Name,HasWeightage__c,MaximumValue__c,Minimum_value__c,MultiSelectFields__c,MultiSelectPredicate__c,MultiSelectSource__c,Step__c,Weightage__c 
    								FROM AuditQuestionType__c LIMIT 50000];
		return listAuditQuestionType;
    }
}