src/objects/AccountPriceBookMember__c.object
<CustomObject>
    <label>AccountPriceBookMember</label>
    <nameField>
        <displayFormat>apm-{00000000}</displayFormat>
        <label>AccountPriceBookMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPriceBookMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountPromotionMember__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>AccountPromotionMembers</relationshipLabel>
        <relationshipName>AccountPromotionMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AccountPromotionMember</label>
    <nameField>
        <label>AccountPromotionMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountPromotionMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Businessprocess__c.object
<CustomObject>
    <label>Businessprocess</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businessprocesss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BusinessProcessParameter__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Value</label>
        <type>Checkbox</type>
    </fields>
    <label>BusinessProcessParameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessProcessParameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HashKey__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>HashKey</label>
    <nameField>
        <displayFormat>HASH-{00000}</displayFormat>
        <label>HashKey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HashKey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Key__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Key</label>
</CustomObject>

src/objects/Organization__c.object
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrganizationAccountMember__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>OrganizationAccountMembers</relationshipLabel>
        <relationshipName>OrganizationAccountMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OrganizationAccountMember</label>
    <nameField>
        <label>OrganizationAccountMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrganizationAccountMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrganizationPromotionMember__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>OrganizationPromotionMembers</relationshipLabel>
        <relationshipName>OrganizationPromotionMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>OrganizationPromotionMembers</relationshipLabel>
        <relationshipName>OrganizationPromotionMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OrganizationPromotionMember</label>
    <nameField>
        <label>OrganizationPromotionMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrganizationPromotionMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>

    <label>ProductGroup</label>
    <nameField>
        <label>ProductGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Promotion__c.object
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UcbHashKey.cls
/*
@Company        :Your SL
@Author         :Jyothi M
@Creation date  :07/08/2015
@Reference      :
*/
public with sharing class UcbHashKey {

    public static void upsertHashKeyValue(List<Sobject> myObject) {

        updateHashKeyAndValue(myObject, generateHashValue());
    }

    public static String generateHashValue() {

        return  String.valueOf(DateTime.now().getTime());

    }

    public static void updateHashKeyAndValue(List<Sobject> myObject, String hashValue) {

        String key =  UcbObjectHelper.getObjectType(myObject);
        System.debug('object type---------------' + key);
        HashKey__c myHashKey;
        List<HashKey__c > listMyHashKey = [SELECT id, Key__c, Value__c, TokenType__c
                                           FROM HashKey__c
                                           WHERE Key__c = :key LIMIT 1];
        if (!listMyHashKey.isEmpty()) {
            myHashKey = listMyHashKey[0];
            myHashKey.Value__c = hashValue;
            myHashKey.TokenType__c = indentifyTokenType(key);
        } else {
            myHashKey = new HashKey__c(Key__c = key, Value__c = hashValue, TokenType__c = indentifyTokenType(key));
        }
        upsert myHashKey;
    }
    private static String indentifyTokenType(String ObjectName) {

        Map<String, String> mapLogic = new Map<String, String>();
        mapLogic.put('Account', 'DataType');
        mapLogic.put('Event', 'DataType');
        mapLogic.put('Order', 'DataType');
        mapLogic.put('Contact', 'DataType');
        mapLogic.put('Businessprocess__c', 'AppType');
        mapLogic.put('BusinessProcessParameter__c', 'AppType');
        mapLogic.put('OrganizationAccountMember__c', 'AppType');
        
        mapLogic.put('Organization__c', 'AppType');
        mapLogic.put('Product2', 'AppType');
        mapLogic.put('ProductGroup__c', 'AppType');
        mapLogic.put('Pricebook2', 'AppType');
        mapLogic.put('Promotion__c', 'AppType');
        mapLogic.put('AccountPromotionMember__c', 'AppType');
        mapLogic.put('AccountPriceBookMember__c', 'AppType');
        mapLogic.put('OrganizationPromotionMember__c', 'AppType');

        return mapLogic.get(ObjectName);

    }
}