src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>VisitScore__c</fullName>
        <label>VisitScore</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AuditResult__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AuditResults</relationshipLabel>
        <relationshipName>AuditResults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AuditResult</label>
    <nameField>
        <label>AuditResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AuditResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestVisitScoreupdate.cls
/*
@Company        :Your SL
@Author         :Jyothi M
@Creation date  :29/07/2015
@Reference      :
*/

@isTest
private class TestVisitScoreupdate {

//This method checks VisitScore field in Account updated or not after inserting the record in AuditResult
static testmethod void visitScoreUpdateAfterInsert(){
Account objAccount=new Account(Name='Genepoint');
insert objAccount;

AuditResult__c objAuditResult=new AuditResult__c(AccountId__c=objAccount.Id,Score__c=3);
insert objAuditResult;
Account objAccount1=[SELECT Id,VisitScore__c FROM Account Where Id=:objAccount.Id];
System.assertEquals(objAuditResult.Score__c,objAccount1.VisitScore__c);
}
}