src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>Hash_Key__c</fullName>
        <label>Hash Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BackGround_Color__c</fullName>
        <label>BackGround Color</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataBinding__c</fullName>
        <label>DataBinding</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PageConfigTypeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfigTypeId</label>
        <referenceTo>PageConfigType__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PageConfigHelper.cls
/***********************************************************************************************
 * MoldTek Technologies
 * Copyrights @ 2015
 * File: PageConfigHelper.Tgr
 *
 * Version        Date            Author                        Description
 * --------       ----------      -----------------------       -------------------
 * 1.0            04/18/2015      Srinivasa Reddy Donapati      Initial Creation
 *
 ************************************************************************************************/
public class PageConfigHelper
{
    // This method is used to populate hash key
    public static void populateHashKey(List<PageConfig__c> newPageConfigs, Map<Id, PageConfig__c> oldPageConfigsMap, Boolean isInsert, Boolean isUpdate)
    {
        Set<Id> appSettingIds = new Set<Id>();
        // capture all the appSettings  to be updated
        PageConfig__c oldPageConfigRecord;

        for(PageConfig__c newPageConfigRecord: newPageConfigs)
        {
            if(isUpdate)
            {
                // get old record
                oldPageConfigRecord = oldPageConfigsMap.get(newPageConfigRecord.Id);
            }
            // collect ids
            if(isInsert
                ||(isUpdate  && 
                        ( newPageConfigRecord.Name != oldPageConfigRecord.Name
                            || newPageConfigRecord.AppSetting__c != oldPageConfigRecord.AppSetting__c
                            || newPageConfigRecord.Image__c != oldPageConfigRecord.Image__c
                            || newPageConfigRecord.BackGround_Color__c!=oldPageConfigRecord.BackGround_Color__c
                            || newPageConfigRecord.AttachmentId__c != oldPageConfigRecord.AttachmentId__c
                            || newPageConfigRecord.BackGround_Color__c != oldPageConfigRecord.BackGround_Color__c
                            || newPageConfigRecord.DataBinding__c != oldPageConfigRecord.DataBinding__c
                            || newPageConfigRecord.Height__c != oldPageConfigRecord.Height__c
                            || newPageConfigRecord.Type__c != oldPageConfigRecord.Type__c
                            || newPageConfigRecord.Width__c != oldPageConfigRecord.Width__c
                            || newPageConfigRecord.XCoordinate__c != oldPageConfigRecord.XCoordinate__c
                            || newPageConfigRecord.YCoordinate__c != oldPageConfigRecord.YCoordinate__c
                            || newPageConfigRecord.PageConfigTypeId__c != oldPageConfigRecord.PageConfigTypeId__c
                           
                        ))
               )            

            {
               appSettingIds.add(newPageConfigRecord.AppSetting__c);
            }

        }
        
        List<AppSettings__c> appSettingsToUpdate = new List<AppSettings__c>();
        // update the hash key and put it in list for updating 
        for(Id currentAppSettingId : appSettingIds)
        {
            String hashKey = UCB_Utility.generateRandomHashKey();
            appSettingsToUpdate.add(new AppSettings__c(Id = currentAppSettingId, Hash_Key__c = hashKey));
        }
        // update AppSettings data
        update appSettingsToUpdate;
    }
    public static void populateHashKeyOnDelete(List<PageConfig__c> listconfig)
    {

        List<AppSettings__c> appSettingsToUpdate = new List<AppSettings__c>();
        // update the hash key and put it in list for updating 
        for(PageConfig__c myPageConfig : listconfig)
        {
            String hashKey = UCB_Utility.generateRandomHashKey();
            appSettingsToUpdate.add(new AppSettings__c(Id = myPageConfig.AppSetting__c, Hash_Key__c = hashKey));
        }
        // update AppSettings data
        update appSettingsToUpdate;
    }
    
}