src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Businessprocess__c.object
<CustomObject>
    <label>Businessprocess</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businessprocesss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BusinessProcessParameter__c.object
<CustomObject>
    <fields>
        <fullName>BusinessprocessId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BusinessprocessId</label>
        <referenceTo>Businessprocess__c</referenceTo>
        <relationshipLabel>BusinessProcessParameters</relationshipLabel>
        <relationshipName>BusinessProcessParameters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BusinessProcessParameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessProcessParameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>attachmentId__c</fullName>
        <label>attachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PageConfigTypeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfigTypeId</label>
        <referenceTo>PageConfigType__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfigType__c.object
<CustomObject>
    <label>PageConfigType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StringCatalogItem__c.object
<CustomObject>
    <label>StringCatalogItem</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StringCatalogItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PageConfigName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfig</label>
        <referenceTo>PageConfig__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UIControlGroupId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControlGroupId</label>
        <referenceTo>UIControlGroup__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UIControlTypeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControlTypeId</label>
        <referenceTo>UIControlType__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttribute__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UIControlAttributeGroupId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControlAttributeGroupId</label>
        <referenceTo>UIControlAttributeGroup__c</referenceTo>
        <relationshipLabel>UIControlAttributes</relationshipLabel>
        <relationshipName>UIControllerAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UIControlAttributeTypeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControlAttributeTypeId</label>
        <referenceTo>UIControlAttributeType__c</referenceTo>
        <relationshipLabel>UIControlAttributes</relationshipLabel>
        <relationshipName>UIControllerAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UIControlId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControlId</label>
        <referenceTo>UIControl__c</referenceTo>
        <relationshipName>UIControllerAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UIControlAttribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttributeGroup__c.object
<CustomObject>
    <label>UIControlAttributeGroup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributeGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttributeType__c.object
<CustomObject>
    <label>UIControlAttributeType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributeType</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlGroup__c.object
<CustomObject>
    <label>UIControlGroup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlType__c.object
<CustomObject>
    <label>UIControlType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PostDeployment.cls
/*
 @Company: YOUR SL
 @Author: KVE
 @Creation date: 16/06/2015
 @Modified date: 22/07/2015
 @Ref: 621
*/
public with sharing class PostDeployment {

	public PostDeployment() {

		if (validate()) {

		} else {
			System.debug('something went wrong');
		}
	}
	// preliminary checks will be executed here
	public boolean validate() {
		return true;
	}

	public static void doDeployment() {

		//String clientId = '3MVG9Rd3qC6oMalUEvDDsZ.dGitMn77csJYM2GPSb11n5tDEvUayiGSmmmbSSsIEHItJPZXEPJmPIDrYwizOP';
		//String clientSecret = '1184065286610443678';
		//String username = 'k.verheyden@nera.centralhub';
		//String password = 'Wasbeer1!G63X9QZCAruidgtRNHlI5N1fN';
		//String url = 'https://eu5.salesforce.com';
		String clientId = '3MVG9Rd3qC6oMalUEvDDsZ.dGigns8FuEpVMh5FD2sLNa3eN1JptaXH1UnR6bzUC5n86ddAhAY4qteuQYVEgU';
		String clientSecret = '9004469196367839452';
		String username = 'imran.s@nera.demodev';
		String password = '1q2w3e4r5th05fZJW9QxSWSh5O8XPe7Agy';
		String url = 'https://eu5.salesforce.com';
		String reqbody = 'grant_type=password&client_id=' + clientId + '&client_secret=' + clientSecret + '&username=' + username + '&password=' + password;
		Http h = new Http();
		HttpRequest req = new HttpRequest();
		req.setBody(reqbody);
		req.setMethod('GET');
		req.setEndpoint( url + '/services/oauth2/token');
		HttpResponse res = h.send(req);

		OAuth2 objAuthenticationInfo = (OAuth2)JSON.deserialize(res.getbody(), OAuth2.class);

		// get the Mobile,AppSettings and Business Process
		if (objAuthenticationInfo.access_token != null) {
			List<MobileDevice__c> myResponse = getResponse(objAuthenticationInfo, 'mobileDevice');
			List<AppSettings__c> myResponseAppsettings = getResponse(objAuthenticationInfo, 'appSetting');
			List<PageConfigType__c> myResponsePageConfigType = getResponse(objAuthenticationInfo, 'pageConfigType');

			List<PageConfig__c> myResponsepageConfig = getResponse(objAuthenticationInfo, 'pageConfig');

			List<UIControlGroup__c> myResponseUiControlGroup = getResponse(objAuthenticationInfo, 'uiControlGroup');
			List<UIControlType__c> myResponseUiControlType = getResponse(objAuthenticationInfo, 'uiControlType');
			List<UIControl__c> myResponseUiControl = getResponse(objAuthenticationInfo, 'uiControl');


			List<UIControlAttribute__c> myResponseUiControlAttribute = getResponse(objAuthenticationInfo, 'uiControlAttribute');
			List<UIControlAttributeType__c> myResponseUiControlAttributeType = getResponse(objAuthenticationInfo, 'uiControlAttributeType');
			List<UIControlAttributeGroup__c> myResponseUiControlAttributeGroup = getResponse(objAuthenticationInfo, 'uiControlAttributeGroup');
			List<Businessprocess__c> myBusinessProcess = getResponse(objAuthenticationInfo, 'businessProcess');
			List<BusinessProcessParameter__c> myBusinessProcessParameters = getResponse(objAuthenticationInfo, 'businessProcessParameter');
			List<StringCatalogItem__c> myStringCatlogItem = getResponse(objAuthenticationInfo, 'stringCatlogItem');
			//-------------------------------------------------

			// OldAttachmentID  Map<  OldParentId, NewParentId >
			Map<Id, Map<Id, Id>> mapOldAttachmentIdNewParentId = new Map<Id, Map<Id, Id>>();

			Map<Id, MobileDevice__c> mapMobileDevices = new Map<Id, MobileDevice__c>();
			for (MobileDevice__c obj : myResponse) {
				Id oldId = obj.Id;
				obj.Id = null;
				mapMobileDevices.put(oldId, obj);
				if (obj.AttachmentId__c <> null) {
					Map<Id, Id> oldMap = new Map<Id, Id>();
					oldMap.put(oldId, null);
					mapOldAttachmentIdNewParentId.put(obj.AttachmentId__c, oldMap);
				}
			}
			insert mapMobileDevices.values();
			for (Id key : mapMobileDevices.keySet()) {
				//the key is the old object Id
				Id oldAttachmentId = mapMobileDevices.get(key).AttachmentId__c;
				(mapOldAttachmentIdNewParentId.get(oldAttachmentId)).put(key, mapMobileDevices.get(key).Id);
			}

			//-------------------------------------------------
			Map<Id, AppSettings__c> mapAppsettings = new Map<Id, AppSettings__c>();
			for (AppSettings__c obj : myResponseAppsettings) {

				Id oldId = obj.Id;
				obj.Id = null;
				//obj.AttachmentId__c = null;
				obj.mobileDevice__c = mapMobileDevices.get(obj.mobileDevice__c).id;
				mapAppsettings.put(oldId, obj);
			}
			insert mapAppsettings.values();

			Map<Id, PageConfigType__c> mapPageConfigType = new Map<Id, PageConfigType__c>();
			for (PageConfigType__c obj : myResponsePageConfigType) {

				Id oldId = obj.Id;
				obj.Id = null;
				mapPageConfigType.put(oldId, obj);
			}
			insert mapPageConfigType.values();

			Map<Id, PageConfig__c> mapPageConfig = new Map<Id, PageConfig__c>();
			for (PageConfig__c obj : myResponsepageConfig) {
				Id oldId = obj.Id;
				obj.Id = null;
				//obj.AttachmentId__c = null;//Comment By Imran

				if (obj.AppSetting__c <> null) {
					obj.AppSetting__c = mapAppsettings.get(obj.AppSetting__c).id;
				}
				if (obj.PageConfigTypeId__c != null) {
					obj.PageConfigTypeId__c = mapPageConfigType.get(obj.PageConfigTypeId__c).id;
				}
				mapPageConfig.put(oldId, obj);
				if (obj.AttachmentId__c <> null) {
					Map<Id, Id> oldMap = new Map<Id, Id>();
					oldMap.put(oldId, null);
					mapOldAttachmentIdNewParentId.put(obj.AttachmentId__c, oldMap);
				}
			}
			insert mapPageConfig.values();
			for (Id key : mapPageConfig.keySet()) {
				//the key is the old object Id
				Id oldAttachmentId = mapPageConfig.get(key).AttachmentId__c;
				if (mapOldAttachmentIdNewParentId.containskey(oldAttachmentId)) {
					(mapOldAttachmentIdNewParentId.get(oldAttachmentId)).put(key, mapPageConfig.get(key).Id);
				}
			}

			Map<Id, UIControlType__c> mapUiControlType = new Map<Id, UIControlType__c>();
			for (UIControlType__c obj : myResponseUiControlType) {
				Id oldId = obj.Id;
				obj.Id = null;
				mapUiControlType.put(oldId, obj);
			}
			insert mapUiControlType.values();

			Map<Id, UIControlGroup__c> mapUiControlGroup = new Map<Id, UIControlGroup__c>();
			for (UIControlGroup__c obj : myResponseUiControlGroup) {
				Id oldId = obj.Id;
				obj.Id = null;
				mapUiControlGroup.put(oldId, obj);
			}
			insert mapUiControlGroup.values();

			Map<Id, UIControl__c> mapUiControl = new Map<Id, UIControl__c>();
			for (UIControl__c obj : myResponseUiControl) {

				Id oldId = obj.Id;
				obj.Id = null;
				//if(mapPageConfig.containsKey(obj.PageConfigName__c)){
				obj.PageConfigName__c = mapPageConfig.containsKey(obj.PageConfigName__c) ? mapPageConfig.get(obj.PageConfigName__c).id : null;
				//}else{
				//obj.PageConfigName__c = null;
				//}

				if (obj.UIControlTypeId__c != null) {
					obj.UIControlTypeId__c = mapUiControlType.get(obj.UIControlTypeId__c).id;
				}

				//if(mapUiControlGroup.containsKey(obj.UIControlGroupId__c)){
				obj.UIControlGroupId__c = mapUiControlGroup.containsKey(obj.UIControlGroupId__c) ? mapUiControlGroup.get(obj.UIControlGroupId__c).id : null;
				//}
				mapUiControl.put(oldId, obj);
				if (obj.AttachmentId__c <> null) {
					Map<Id, Id> oldMap = new Map<Id, Id>();
					oldMap.put(oldId, null);
					mapOldAttachmentIdNewParentId.put(obj.AttachmentId__c, oldMap);
				}
			}
			insert mapUiControl.values();
			for (Id key : mapUiControl.keySet()) {
				//the key is the old object Id
				Id oldAttachmentId = mapUiControl.get(key).AttachmentId__c;
				if (mapOldAttachmentIdNewParentId.containskey(oldAttachmentId)) {
					(mapOldAttachmentIdNewParentId.get(oldAttachmentId)).put(key, mapUiControl.get(key).Id);
				}
			}

			Map<Id, UIControlAttributeType__c> mapUiControlAttributeType = new Map<Id, UIControlAttributeType__c>();
			for (UIControlAttributeType__c obj : myResponseUiControlAttributeType) {
				Id oldId = obj.Id;
				obj.Id = null;
				mapUiControlAttributeType.put(oldId, obj);
			}
			insert mapUiControlAttributeType.values();

			Map<Id, UIControlAttributeGroup__c> mapUIControlAttributeGroup = new Map<Id, UIControlAttributeGroup__c>();
			for (UIControlAttributeGroup__c obj : myResponseUiControlAttributeGroup) {
				Id oldId = obj.Id;
				obj.Id = null;
				mapUIControlAttributeGroup.put(oldId, obj);
			}
			insert mapUIControlAttributeGroup.values();

			Map<Id, UIControlAttribute__c> mapUIControlAttribute = new Map<Id, UIControlAttribute__c>();
			for (UIControlAttribute__c obj : myResponseUiControlAttribute) {
				Id oldId = obj.Id;
				obj.Id = null;
				obj.UIControlAttributeTypeId__c = obj.UIControlAttributeTypeId__c != null ? mapUiControlAttributeType.get(obj.UIControlAttributeTypeId__c).id : null;
				obj.UIControlAttributeGroupId__c = obj.UIControlAttributeGroupId__c != null ? mapUIControlAttributeGroup.get(obj.UIControlAttributeGroupId__c).id : null;
				//if(mapUiControl.containskey(obj.UIControlId__c)){
				obj.UIControlId__c = mapUiControl.containskey(obj.UIControlId__c) ? mapUiControl.get(obj.UIControlId__c).id : null ;
				//}
				//else{
				//obj.UIControlId__c = null;
				//}
				mapUIControlAttribute.put(oldId, obj);
				if (obj.AttachmentId__c <> null) {
					Map<Id, Id> oldMap = new Map<Id, Id>();
					oldMap.put(oldId, null);
					mapOldAttachmentIdNewParentId.put(obj.AttachmentId__c, oldMap);
				}
			}
			insert mapUIControlAttribute.values();
			for (Id key : mapUIControlAttribute.keySet()) {
				//the key is the old object Id
				Id oldAttachmentId = mapUIControlAttribute.get(key).AttachmentId__c;
				if (mapOldAttachmentIdNewParentId.containskey(oldAttachmentId)) {
					(mapOldAttachmentIdNewParentId.get(oldAttachmentId)).put(key, mapUIControlAttribute.get(key).Id);
				}
			}

			//---Business Process---Start---------------

			Map<Id, Businessprocess__c> mapBusinessProcess = new Map<Id, Businessprocess__c>();
			for (Businessprocess__c obj : myBusinessProcess) {
				Id oldId = obj.Id;
				obj.Id = null;
				mapBusinessProcess.put(oldId, obj);
			}
			insert mapBusinessProcess.values();

			Map<Id, BusinessProcessParameter__c> mapBusinessProcessParameters = new Map<Id, BusinessProcessParameter__c>();
			for (BusinessProcessParameter__c obj : myBusinessProcessParameters) {
				Id oldId = obj.Id;
				obj.Id = null;
				obj.BusinessprocessId__c = mapBusinessProcess.get(obj.BusinessprocessId__c).Id;
				mapBusinessProcessParameters.put(oldId, obj);
			}
			insert mapBusinessProcessParameters.values();

			//---Business Process---End---------------
			Map<Id, StringCatalogItem__c> mapStringCatlogItem = new Map<Id, StringCatalogItem__c>();
			for (StringCatalogItem__c obj : myStringCatlogItem) {
				Id oldId = obj.Id;
				obj.Id = null;
				mapStringCatlogItem.put(oldId, obj);
			}
			insert mapStringCatlogItem.values();

			//Map<Id,Map<Id,Id>> mapOldAttachmentIdNewParentId
			System.debug('SIZE OF BATCH ---->  ' + mapOldAttachmentIdNewParentId.size());
			Database.executeBatch(new BatchPostDeployment(mapOldAttachmentIdNewParentId), 1);
		}
	}
	//attachment oldId / parentId

	public static List<Sobject> getResponse(OAuth2 objAuthenticationInfo, String objectType) {
		String url = 'https://eu5.salesforce.com';
		Http h1 = new Http();
		HttpRequest requestMobileAndApp = new HttpRequest();
		requestMobileAndApp.setHeader('Authorization', 'Bearer ' + objAuthenticationInfo.access_token);
		requestMobileAndApp.setHeader('Content-Type', 'application/json');
		requestMobileAndApp.setHeader('accept', 'application/json');
		requestMobileAndApp.setMethod('GET');
		requestMobileAndApp.setEndpoint(url + '/services/apexrest/Deployment/?requestType=' + objectType);

		HttpResponse myResponse = h1.send(requestMobileAndApp);
		String myJson = myResponse.getBody();
		myJson = '{"MobileDevice__c":' + myJson + '}';

		JSONParser parser = JSON.createParser(myJson);

		List<Sobject> listMyResponseObjects = new List<Sobject>();
		while (parser.nextToken() != null) {
			if (parser.getCurrentToken() == JSONToken.START_ARRAY) {
				while (parser.nextToken() != null) {
					if (parser.getCurrentToken() == JSONToken.START_OBJECT) {
						Sobject mobile = (Sobject)parser.readValueAs(Sobject.class);
						listMyResponseObjects.add(mobile);
						//parser.skipChildren();
					}
				}
			}
		}
		return listMyResponseObjects;
	}
	//#region wrappers {
	public class OAuth2 {

		public String id {get; set;}
		public String issued_at {get; set;}
		public String instance_url {get; set;}
		public String signature {get; set;}
		public String access_token {get; set;}

	}
	//
	//}
}