src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <description>the semantic version for the app</description>
        <label>version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>height__c</fullName>
        <label>height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>operatingSystem__c</fullName>
        <label>operatingSystem</label>
        <picklist>
            <picklistValues>
                <fullName>IOS 8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDROID 5.1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>width__c</fullName>
        <label>width</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestWsPageConfig.cls
/*
 @Company: YOUR SL  
 @Author: Asritha   
 @Creation date: 18/8/2015   
 @Ref: xxxx
*/
@isTest
private class TestWsPageConfig {
	
	static testmethod void doGet()	{

		MobileDevice__c mobiledeviceobj = new MobileDevice__c ( Name = 'IPadAir2',operatingSystem__c = 'IOS 8',height__c = 768,width__c = 1024);
		insert mobiledeviceobj;
		AppSettings__c appSettingObj = new AppSettings__c( Name = 'IPadAir2',mobileDevice__c = mobiledeviceobj.Id,version__c = '1.0.0.0');
		insert appsettingObj;
		PageConfig__c pageConfigobj = new PageConfig__c( Name = 'SplashScreen',AppSetting__c = appsettingObj.Id);
		insert pageConfigobj;
		Attachment attach = new Attachment(Name = 'attachName', body = Blob.valueOf('NeraLogo'),parentId = pageConfigobj.id);
		insert attach;
		RestRequest req = new RestRequest();
		req.requestURI = 'https://eu5.salesforce.com/services/apexrest/PageConfig';
		req.httpMethod = 'Get';
		RestResponse res = new RestResponse();
		RestContext.request = req;
		RestContext.response = res;
		// WsPageConfig.WsGet();
	}
	
}