src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Businessprocess__c.object
<CustomObject>
    <label>Businessprocess</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businessprocesss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BusinessProcessParameter__c.object
<CustomObject>
    <label>BusinessProcessParameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessProcessParameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfigType__c.object
<CustomObject>
    <label>PageConfigType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttribute__c.object
<CustomObject>
    <label>UIControlAttribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttributeGroup__c.object
<CustomObject>
    <label>UIControlAttributeGroup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributeGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttributeType__c.object
<CustomObject>
    <label>UIControlAttributeType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributeType</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlGroup__c.object
<CustomObject>
    <label>UIControlGroup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlType__c.object
<CustomObject>
    <label>UIControlType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CtrOrgRecordCount.cls
public with sharing class CtrOrgRecordCount {
    public Integer totalCount{get;set;}  
    public Map<String,Integer> recordCount{
        get{
            Map<String,Integer> mapReccordCount = new Map<String,Integer>();
            mapReccordCount.put('MobileDevice',[SELECT Count() FROM MobileDevice__c LIMIT 50000]);
            mapReccordCount.put('AppSettings',[SELECT Count() FROM AppSettings__c LIMIT 50000]);
            mapReccordCount.put('PageConfig',[SELECT Count() FROM PageConfig__c LIMIT 50000]);
            mapReccordCount.put('UIControl',[SELECT Count() FROM UIControl__c LIMIT 50000]);
            mapReccordCount.put('UIControlGroup',[SELECT Count() FROM UIControlGroup__c LIMIT 50000]);
            mapReccordCount.put('UIControlType',[SELECT Count() FROM UIControlType__c LIMIT 50000]);
            mapReccordCount.put('UIControlAttribute',[SELECT Count() FROM UIControlAttribute__c LIMIT 50000]);
            mapReccordCount.put('UIControlAttributeGroup',[SELECT Count() FROM UIControlAttributeGroup__c LIMIT 50000]);
            mapReccordCount.put('UIControlAttributeType',[SELECT Count() FROM UIControlAttributeType__c LIMIT 50000]);
            mapReccordCount.put('PageConfigType',[SELECT Count() FROM PageConfigType__c LIMIT 50000]);
            mapReccordCount.put('Businessprocess',[SELECT Count() FROM Businessprocess__c LIMIT 50000]);
            mapReccordCount.put('BusinessProcessParameter',[SELECT Count() FROM BusinessProcessParameter__c LIMIT 50000]);
            totalCount =0;
            for(Integer i :  mapReccordCount.values()){
                totalCount = totalCount+i;
            }                       
            return mapReccordCount;
        }set;
    }
}