src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>AppVersion__c</fullName>
        <label>AppVersion</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hash_Key__c</fullName>
        <label>Hash Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HistoryUserKeyGenerated__c.object
<CustomObject>
    <fields>
        <fullName>deploymentData__c</fullName>
        <label>deploymentData</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>publicKey__c</fullName>
        <label>publicKey</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>HistoryUserKeyGenerated</label>
    <nameField>
        <label>HistoryUserKeyGenerated Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HistoryUserKeyGenerateds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Key__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>ClientId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerSecret__c</fullName>
        <label>CustomerSecret</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Key</label>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CtrGenerateKeyForUSer.cls
/*
@Company: YOUR SL  
@Author: K. Verheyden
@Creation date: 14.04.2015  
@Ref: xxxxxxx
*/ 
public with sharing class CtrGenerateKeyForUSer {
    
    public HistoryUserKeyGenerated__c userKey { get;set;}
    public String selectedAppSettingId {get; set;}
    public List<SelectOption> appSettingvalues {get;set;}

    public CtrGenerateKeyForUSer() {
        
        this.userKey = new HistoryUserKeyGenerated__c();
        
        appSettingvalues = new list<SelectOption>();
        for(AppSettings__c currentAppSetting : [SELECT id, Name, AppVersion__c, Hash_Key__c, mobileDevice__c 
                                                FROM AppSettings__c
                                                LIMIT 50000])
        {
            appSettingvalues.add(new SelectOption(currentAppSetting.Id, currentAppSetting.Name));
        }
        
    }

    public void generateKeyForUser(){

        UcbCrypto cryptor = new UcbCrypto();
        key__c key = key__c.getInstance('neradevelopment'); 
        jsonInfo jsondata = new jsonInfo();
        jsonData.clientId = key.ClientId__c;
        jsonData.secretkey = key.CustomerSecret__c;
        jsonData.appVersion = selectedAppSettingId;
        List<User> userData = [Select id from User where username =: key.UserName__c];
        if(!userData.isempty())
        {
            jsonData.userId = userData[0].id;
        }
        String  jsonResponse = JSON.serialize(jsonData);
        System.debug('jsonResponse ==>'+jsonResponse );
        UcbCrypto.Payload encryptedDate = cryptor.Encrypt(jsonResponse );
        System.debug('Payload data-->'+EncodingUtil.base64Encode(encryptedDate.data ));
        
        //UcbCrypto.Payload encryptedDate = cryptor.Encrypt('userid00000000,comsumerkey,cosnumercode ,token  ,systemuser,systempassword,appversion');
        
        this.userKey.publicKey__c = String.valueof(encryptedDate.cryptoKey);



        String encodedBlob = EncodingUtil.base64Encode(encryptedDate.data);

        this.userKey.deploymentData__c = encodedBlob;
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,encodedBlob);
        ApexPages.addMessage(myMsg);
    }

    public void sendUserKey(){

    }
    
    
    public class jsonInfo
    {
        public String clientId;
        public String secretKey;
        //public String userName;
        public String userId;
        public String appVersion;
        
        jsonInfo parse(String json)
        {
            return (jsonInfo) System.JSON.deserialize(json, jsonInfo.class);
        }
    
    }
    
}