src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>AppVersion__c</fullName>
        <label>AppVersion</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>XBezel__c</fullName>
        <label>XBezel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XFrame__c</fullName>
        <label>XFrame</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YBezel__c</fullName>
        <label>YBezel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YFrame__c</fullName>
        <label>YFrame</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>attachmentId__c</fullName>
        <label>attachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>height__c</fullName>
        <label>height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>width__c</fullName>
        <label>width</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BackGround_Color__c</fullName>
        <label>BackGround Color</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POIType__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>POIType</label>
    <nameField>
        <label>POIType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POIType</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POIType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POIType</label>
        <referenceTo>POIType__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PageConfigName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfig</label>
        <referenceTo>PageConfig__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PoiIconImageId__c</fullName>
        <label>PoiIconImageId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlType__c.object
<CustomObject>
    <label>UIControlType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUpdatePoIIconimageId.cls
/*
@Company        :Your SL
@Author         :Jyothi
@Creation date  :08/09/2015
@Reference      :
*/

@isTest
public class TestUpdatePoIIconimageId {

      //This method checks whether PoiIconImageId__c field of UICOntroll object upadated (with AttachmentId of POIType object) or not after inserting the image in POIType object
    static testmethod void UpdatePoIIconimageIdinUICnt(){
    
    
      POIType__c objPOIType=new POIType__c(Name='Cooler');
      insert objPOIType;
       Attachment attach = new Attachment(Name = 'iPadAir2vector', body = Blob.valueOf('attachBody'), parentId = objPOIType.id);
        insert attach;
        
        objPOIType.AttachmentId__c=attach .Id;
        update objPOIType;
        system.debug('-----POITY'+objPOIType);
        
        MobileDevice__c objmobileDevice = new MobileDevice__c(Name = 'Samsung', height__c = 4, width__c = 4, XBezel__c = 90.0, YBezel__c = 34.0, XFrame__c = 727.0, YFrame__c = 563.0 );
        insert objmobileDevice;
        
        AppSettings__c objAppSettings = new AppSettings__c(mobileDevice__c = objmobileDevice.Id, Name = 'IPadAir2', AppVersion__c = 123);
        insert objAppSettings;
        
        PageConfig__c objPageConfig = new PageConfig__c(Name = 'LoginPage', AppSetting__c = objAppSettings.Id, BackGround_Color__c = '#465568');
        insert objPageConfig;
        
        UIControlType__c objUIControlType = new UIControlType__c(Name = 'POI');
        insert objUIControlType;
        UIControl__c objUIControl=new UIControl__c(Name='CoolerPOI',Height__c=12,YCoordinate__c=3,PageConfigName__c=objPageConfig .Id,POIType__c=objPOIType.Id,Type__c=objUIControlType.Id );
        insert objUIControl;
        UIControl__c objUIControl1=[SELECT Id,PoiIconImageId__c FROM UIControl__c ];
        
        
        system.assertEquals( objPOIType.AttachmentId__c,objUIControl1.PoiIconImageId__c );
        
        
    }


}