src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>AppSettingImage__c</fullName>
        <label>AppSettingImage</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>AppVersion__c</fullName>
        <label>AppVersion</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hash_Key__c</fullName>
        <label>Hash Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <description>the semantic version for the app</description>
        <label>version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Businessprocess__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>Businessprocess</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businessprocesss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BusinessProcessParameter__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>BusinessProcessParameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessProcessParameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>XBezel__c</fullName>
        <label>XBezel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XFrame__c</fullName>
        <label>XFrame</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YBezel__c</fullName>
        <label>YBezel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YFrame__c</fullName>
        <label>YFrame</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>attachmentId__c</fullName>
        <label>attachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>height__c</fullName>
        <label>height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>operatingSystem__c</fullName>
        <label>operatingSystem</label>
        <picklist>
            <picklistValues>
                <fullName>IOS 8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDROID 5.1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>width__c</fullName>
        <label>width</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BackGround_Color__c</fullName>
        <label>BackGround Color</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataBinding__c</fullName>
        <label>DataBinding</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PageConfigTypeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfigTypeId</label>
        <referenceTo>PageConfigType__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfigType__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>PageConfigType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StringCatalogItem__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>StringCatalogItem</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StringCatalogItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>FieldName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>FieldType</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextLabel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsHidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsHidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttribute__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsHidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsHidden</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlAttribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttributeGroup__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlAttributeGroup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributeGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttributeType__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlAttributeType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributeType</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlGroup__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlGroup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlType__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>UIControlType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WsDeployment.cls
/*
@Company:Your SL
@Author:Veera
@Creation date:4/6/2015
Reference: Ticket no 463
*/
@RestResource(urlmapping = '/Deployment/*')

global class WsDeployment implements UcbWs {
public static Map<Id,BusinessProcessParameter__c> businessProcessParameterMap;
public static UcbWsResponse doReply(UcbWsRequest request) {
return new UcbWsResponse();

}
@HttpGet
global static void wsGplet() {
UcbWsRequest myRequest = new UcbWsRequest(RestContext.request);
if(myRequest.attachMentId <> null){
RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnAttachMent(myRequest.attachMentId)));
}
if(myRequest.appSetting == 'mobileDevice'){ 
   RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnMobileDevice()));
        }    
        else if(myRequest.appSetting == 'appSetting'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnAppSettings()));
        } 
        else if(myRequest.appSetting == 'pageConfig'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnPageConfig()));
        }
        else if(myRequest.appSetting == 'uiControl'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnUiControl()));
        } 
        else if(myRequest.appSetting == 'uiControlAttribute'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnUiControlAttribute()));
        } 
        else if(myRequest.appSetting == 'uiControlType'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnUiControlType()));
        }
        else if(myRequest.appSetting == 'uiControlGroup'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnUiControlGroup()));
            RestContext.response.addHeader('Content-Type', 'application/json');
        }
        else if(myRequest.appSetting == 'uiControlAttributeType'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnUiCntrlAttType()));
        } 
        else if(myRequest.appSetting == 'uiControlAttributeGroup'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnUiCntrlAttGroup()));
        } 
        else if(myRequest.appSetting == 'pageConfigType'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(retunPageConfigType()));           
        } 
        else if(myRequest.appSetting == 'businessProcessParameter'){
           RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnBusinessProcessParameter()));
        }
        else if(myRequest.appSetting == 'businessProcess'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnBusinessProcess()));
        }
        else if(myRequest.appSetting == 'stringCatlogItem'){
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(returnStringCatlogItem()));
        }
        RestContext.response.addHeader('Content-Type', 'application/json');  
    }  

    public static List<MobileDevice__c> returnMobileDevice(){                                                                    

        List<MobileDevice__c> mobDev = [SELECT ID,Name,AttachmentId__c,Height__c,Image__c,IsDefault__c,OperatingSystem__c,Width__c,XBezel__c,XFrame__c,YBezel__c,YFrame__c 
                                        FROM MobileDevice__c 
                                        WHERE IsDefault__c=true];
        return mobDev;
    }

    public static List<AppSettings__c> returnAppSettings(){
  
          List<AppSettings__c> listAppSetting = [SELECT ID,Name,AppSettingImage__c,AppVersion__c,Hash_Key__c,IsDefault__c,MobileDevice__c,Version__c 
                                                 FROM AppSettings__c
                                                 WHERE IsDefault__c = true];   
         return listAppSetting;
    }

    public static List<PageConfig__c> returnPageConfig(){   

        List<PageConfig__c> pageConfig = [SELECT Name,ID,AppSetting__c,AttachmentId__c,BackGround_Color__c,DataBinding__c,Height__c,Image__c,IsDefault__c,PageConfigTypeId__c,Type__c,Width__c,XCoordinate__c,YCoordinate__c 
                                         FROM PageConfig__c
                                         WHERE IsDefault__c = true];
        return pageConfig;
    }
    public static List<UIControl__c> returnUiControl(){

        List<UIControl__c> uiControl = [SELECT Name,AttachmentId__c,FieldName__c,FieldType__c,Height__c,Image__c,IsDefault__c,IsHidden__c,Order__c,PageConfigName__c,Type__c,UIControlGroupId__c,UIControlTypeId__c,Value__c,Width__c,XCoordinate__c,YCoordinate__c 
                                        FROM UIControl__c
                                        WHERE IsDefault__c = true];
        return uiControl;
    }

    public static List<UIControlAttribute__c> returnUiControlAttribute(){
       
            List<UIControlAttribute__c> uiControlAttribute = [SELECT Name,AttachmentId__c,DataObjectType__c,Image__c,IsDefault__c,IsHidden__c,Order__c,UIControlAttributeGroupId__c,UIControlAttributeTypeId__c,UIControlId__c,Value__c
                                                                FROM UIControlAttribute__c 
                                                                WHERE IsDefault__c = true];
        return uiControlAttribute;
    }
    
    public static List<UIControlType__c> returnUiControlType(){
       
            List<UIControlType__c> uiControlType = [SELECT Name,IsDefault__c FROM UIControlType__c WHERE IsDefault__c=true];
            return uiControlType;
    }
    
    public static List<UIControlGroup__c> returnUiControlGroup(){
      
            List<UIControlGroup__c> uiControlGroup = [SELECT Name,IsDefault__c FROM UIControlGroup__c WHERE IsDefault__c=true];
            return uiControlGroup;
    }
    
    public static List<UIControlAttributeType__c> returnUiCntrlAttType(){
        
            List<UIControlAttributeType__c> uiCintrolAttributeType= [SELECT Name,IsDefault__c FROM UIControlAttributeType__c WHERE IsDefault__c=true];
            return uiCintrolAttributeType;
    }
   
    public static List<UIControlAttributeGroup__c> returnUiCntrlAttGroup(){
        
            List<UIControlAttributeGroup__c> uiControlAttributeGroup = [SELECT Name,IsDefault__c FROM UIControlAttributeGroup__c WHERE IsDefault__c=true];
            return uiControlAttributeGroup;
    }
   
    public static List<PageConfigType__c> retunPageConfigType(){
       
        List<PageConfigType__c> pageConfigType = [SELECT Name,IsDefault__c FROM PageConfigType__c WHERE IsDefault__c=true];
        return pageConfigType;
    }
   
    public static List<Businessprocess__c> returnBusinessProcess(){
       
        List<Businessprocess__c> businessProcess = [SELECT Name,IsDefault__c FROM Businessprocess__c WHERE IsDefault__c=true];
        return businessProcess;
    }
    
    public static List<BusinessProcessParameter__c> returnBusinessProcessParameter(){
        List<BusinessProcessParameter__c> businessProcessParameter = [SELECT Name,IsDefault__c,BusinessprocessId__c,Value__c,ValueNumber__c,Values__c 
                                                                        FROM BusinessProcessParameter__c
                                                                        WHERE IsDefault__c=true];
        return businessProcessParameter;
    }
    public static List<StringCatalogItem__c> returnStringCatlogItem(){
        List<StringCatalogItem__c> stringCatlogItem = [SELECT  Id,Name,EnumCode__c,IsDefault__c,Language__c,Text__c,Type__c 
                                                        FROM StringCatalogItem__c
                                                        WHERE IsDefault__c = true];
        return stringCatlogItem;
    }
    public static AttachmentWrapper returnAttachMent(String attachMentId){
        if(attachMentId <> null && attachMentId <> ''){
            try{
                    Attachment att = [SELECT Id,Name,Body,ParentId FROM Attachment where ID=:attachMentId];
                    AttachmentWrapper attWrap = new AttachmentWrapper();      
                        attWrap.id = att.ID;
                        attWrap.name = att.Name;
                        attWrap.body = att.Body;
                        attWrap.parentId = att.ParentId;
                    return attWrap;
                }catch(Exception e){
                    system.debug('erroe-------------------'+e.getMessage());
                }            
        } 
        return null;      
    }
    public class AttachmentWrapper{
        public String name;
        public Id id;
        public Blob body;
        public String parentId;
    }
}