src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PageConfigName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfig</label>
        <referenceTo>PageConfig__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MobileAppSettingsController.cls
/*
 @Company: YOUR SL  
 @Author: Your name   
 @Creation date: dd/mm/yyyy   
 @Ref: xxxxxxx
*/
Public with sharing class MobileAppSettingsController {


 Public List<PageConfig__c> PageConfiglist{Set; Get;}
 Public List<UIControl__c> Uicontrollerslist{Set; Get;}
 Public List<AppSettings__c> AppSettingslist{Set; Get;}
 Public List<UIControl__c> Uicontrollerslist1 { get; set; }
 Public List<SelectOption> listpage {Get;Set;}
 Public String PageConfigselect{Get;Set;}
 Public String Selectedappsettings{Set; Get;}
 Public String Selecteduicontrollers{Get;Set;}
 

        Public Map <String,AppSettings__c> mapstrapps = new Map <String,AppSettings__c>();
        Public Map <String,PageConfig__c> mapstrpage = new Map <String,PageConfig__c>();
    
        Public MobileAppSettingsController()
        {
        AppSettingslist = New List<AppSettings__c>();

            For(AppSettings__c app:[Select id,name,(select id,name from PageConfigs__r) From AppSettings__c])
            {
            AppSettingslist.add(app);
            mapstrapps.Put(app.ID,app);
            }
 
        }
        Public void Pageuicon() {

        PageConfiglist = new List<PageConfig__c>();
           if(PageConfigselect!='none')
            {
                for(PageConfig__c pagcon:[select id,name,(select name,Height__c,Width__c,XCoordinate__c,YCoordinate__c from UIControls__r) from PageConfig__c where id=:PageConfigselect])
                {
                PageConfiglist.add(pagcon);
                mapstrpage.put(pagcon.id,pagcon);            
                }
            
        Uicontrollerslist = new list<UIControl__c>();
        Uicontrollerslist = mapstrpage.Get(PageConfigselect).UIControls__r;
        
         }

        }
    
        Public List<SelectOption> getPageConfig() { 
            
        return listpage;
        } 
        
        
        Public void getappsettings() {     
        PageConfiglist = new List<PageConfig__c>();               
        PageConfiglist = mapstrapps.Get(selectedappsettings).PageConfigs__r;

            listpage = new List<SelectOption>();

            listpage.add(new SelectOption('None','None'));              
            for(PageConfig__c pa: PageConfiglist){   

            listpage.add(new SelectOption(pa.id,pa.name));                              
            } 
        }
        
        Public void getuicontrollers() {

        Uicontrollerslist1 = new List<UIControl__c>();   

            for(UIControl__c uicon:[select id,name,Height__c,Width__c,XCoordinate__c,YCoordinate__c from UIControl__c where id=:selecteduicontrollers])
            {
            Uicontrollerslist1.add(uicon);           
            }           
        }
         
            
             
         
        Public PageReference Cancelit() {
        return null;
        }


        Public PageReference saveit() {
        
        return null;
        }




}