src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CtrlPictureOfSuccess.cls
public with sharing class CtrlPictureOfSuccess {

    public String selectAppseting { get; set; }

    public List<PageConfig__c> listofPictureOfSuccess { get; set; }

    public List<Selectoption> appsettingList { get; set; }
   


    public void GetPosrec() {
    
   listofPictureOfSuccess  = [select id,Name from PageConfig__c where AppSetting__c=:selectAppseting];
   
  system.debug('........linenumber15......' +ListofPictureOfSuccess);
 
 
      
    }

 public CtrlPictureOfSuccess()
 {
 
 appsettingList =new List<selectoption>();

List<AppSettings__c> listAppsetting = [SELECT id,Name From  AppSettings__c  Limit 10];

 for(AppSettings__c appSettring : listAppsetting)
 {

appsettingList.add(new Selectoption(appSettring.id,appSettring.Name));


 }

 }
 
 
 
  
}