src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>Hash_Key__c</fullName>
        <label>Hash Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsHidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsHidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PageConfigName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfig</label>
        <referenceTo>PageConfig__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>244</length>
        <type>Text</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControlAttribute__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataObjectType__c</fullName>
        <label>DataObjectType</label>
        <length>244</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsHidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsHidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UIControlAttributeGroupId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControlAttributeGroupId</label>
        <referenceTo>UIControlAttributeGroup__c</referenceTo>
        <relationshipLabel>UIControlAttributes</relationshipLabel>
        <relationshipName>UIControllerAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UIControlAttributeTypeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControlAttributeTypeId</label>
        <referenceTo>UIControlAttributeType__c</referenceTo>
        <relationshipLabel>UIControlAttributes</relationshipLabel>
        <relationshipName>UIControllerAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UIControlId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIControlId</label>
        <referenceTo>UIControl__c</referenceTo>
        <relationshipName>UIControllerAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>244</length>
        <type>Text</type>
    </fields>
    <label>UIControlAttribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControlAttributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UIControlAttributeHelper.cls
/*
@Company:
@Author:pavan kumar 
@Creation Date:6/4/2015
@Reference:
*/
public class UIControlAttributeHelper{

    // This method is used to populate hash key
    public static void populateHashKey( List<UIControlAttribute__c> newUiControlAttributes, Map<Id, UIControlAttribute__c> oldUiControlAttributesMap, Boolean isInsert, Boolean isUpdate)
    {
        Set<Id> uiControlNameIds  = new Set<Id>();
                       
        for(UIControlAttribute__c newUiControlAttributesRecord : newUiControlAttributes)
        {
            UIControlAttribute__c oldUiControlAttributesRecord;
            if(isUpdate)
            {
                // get old record
                oldUiControlAttributesRecord = oldUiControlAttributesMap.get(newUiControlAttributesRecord.Id);
            }
            // collect ids
            if( isInsert 
                || ( isUpdate
                && ( newUiControlAttributesRecord.Name != oldUiControlAttributesRecord.Name
                     ||   newUiControlAttributesRecord.DataObjectType__c != oldUiControlAttributesRecord.DataObjectType__c
                     ||   newUiControlAttributesRecord.Value__c != oldUiControlAttributesRecord.Value__c
                     ||   newUiControlAttributesRecord.Order__c != oldUiControlAttributesRecord.Order__c                      
                     ||   newUiControlAttributesRecord.UIControlId__c != oldUiControlAttributesRecord.UIControlId__c
                     ||   newUiControlAttributesRecord.UIControlAttributeGroupId__c != oldUiControlAttributesRecord.UIControlAttributeGroupId__c
                     ||   newUiControlAttributesRecord.UIControlAttributeTypeId__c != oldUiControlAttributesRecord.UIControlAttributeTypeId__c
                     ||   newUiControlAttributesRecord.Image__c != oldUiControlAttributesRecord.Image__c
                     ||   newUiControlAttributesRecord.IsHidden__c != oldUiControlAttributesRecord.IsHidden__c
                     ||   newUiControlAttributesRecord.AttachmentId__c !=oldUiControlAttributesRecord.AttachmentId__c
                     ||   newUiControlAttributesRecord.IsDefault__c != oldUiControlAttributesRecord.IsDefault__c 
                     ))  
               )
               
            {
                uiControlNameIds.add(newUiControlAttributesRecord.UIControlId__c);
            }
        }  
        List<UIControl__c> modifiedUiCtrls = new List<UIControl__c>([SELECT Id, Name, PageConfigName__c 
                                                                     FROM UIControl__c 
                                                                     WHERE id IN: uiControlNameIds]);  
         Set<Id> setModifiedPageConfigIds = new Set<Id>();
         
       
       for(UIControl__c modifiedPageConfigId : modifiedUiCtrls)
        {
            setModifiedPageConfigIds.add(modifiedPageConfigId.PageConfigName__c);
        }
                
        List<AppSettings__c> appSettingsToUpdate = new List<AppSettings__c>();
        Set<Id> appSettingIds = new Set<Id>();
        // capture all the appSettings  to be updated
        for(PageConfig__c currentPageConfig :[SELECT id, AppSetting__c 
                                              FROM PageConfig__c 
                                              WHERE id IN: setModifiedPageConfigIds])
        {
            appSettingIds.add(currentPageConfig.AppSetting__c);
        }
        // update the hash key and put it in list for updating
        for(Id currentAppSettingId : appSettingIds)
        {
            String hashKey = UCB_Utility.generateRandomHashKey();
            appSettingsToUpdate.add(new AppSettings__c(Id = currentAppSettingId, Hash_Key__c = hashKey));
        }
        // update AppSettings data
        update appSettingsToUpdate;                                
   }
   
   public static void populateHashKeyOnDelete( List<UIControlAttribute__c> listUiControlAttribute)
    {

        List<AppSettings__c> appSettingsToUpdate = new List<AppSettings__c>();
        List<PageConfig__c> pageConfigs = new List<PageConfig__c>();
        
        List<UIControl__c> listUiControl = [SELECT Id,PageConfigName__c
                                            FROM UIControl__c
                                            LIMIT 50000];
        List<PageConfig__c> listPageConfigs=[SELECT Id,AppSetting__c 
                                             FROM PageConfig__c
                                             LIMIT 50000];

        for(UIControlAttribute__c myUiControlAttribute : listUiControlAttribute)
        {
            for(UIControl__c myUiControl : listUiControl)
            {
                if(myUiControl.Id == myUiControlAttribute.UIControlId__c)
                for(PageConfig__c myPageConfig :listPageConfigs)
                {
                    if(myPageConfig.Id == myUiControl.PageConfigName__c)
                    {
                        pageConfigs.add(myPageConfig);
                        break;
                    }
                }
            }                
        }
        // update the hash key and put it in list for updating     
        for(PageConfig__c myFinalPageConfig : pageConfigs)
        {
            String hashKey = UCB_Utility.generateRandomHashKey();
            appSettingsToUpdate.add(new AppSettings__c(Id = myFinalPageConfig.AppSetting__c, Hash_Key__c = hashKey));
        }       
        // update AppSettings data
        update appSettingsToUpdate;
    }        
}