src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>Hash_Key__c</fullName>
        <label>Hash Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>FieldName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>FieldType</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextLabel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsHidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsHidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PageConfigName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfig</label>
        <referenceTo>PageConfig__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>244</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UIControlHelper.cls
/***********************************************************************************************
 * MoldTek Technologies
 * Copyrights @ 2015
 * File: UIControlTgrHelper.Tgr
 *
 * Version        Date            Author                        Description
 * --------       ----------      -----------------------       -------------------
 * 1.0            04/18/2015      Srinivasa Reddy Donapati      Initial Creation
 *
 ************************************************************************************************/

/************************************************************************************************
 * This is trigger helper class that is used to update the hashkey when UI Control records are modified
 ************************************************************************************************/
public class UIControlHelper
{
    // This method is used to populate hash key
    public static void populateHashKey( List<UIControl__c> newUiControls, Map<Id, UIControl__c> oldUiControlsMap, Boolean isInsert, Boolean isUpdate)
    {

        Set<Id> PageConfigNameIds = new Set<Id>();
       
       
        // capture all the pageConfig ids of UI Controls that were changed
        for(UIControl__c newUiControlRecord : newUiControls)
        {
            UIControl__c oldUiControlRecord;
            if(isUpdate)
            {
                // get old record
                oldUiControlRecord = oldUiControlsMap.get(newUiControlRecord.Id);
            }
            // collect ids
            if( isInsert 
                || ( isUpdate
                     && ( newUiControlRecord.Name != oldUiControlRecord.Name
                        || newUiControlRecord.PageConfigName__c !=oldUiControlRecord.PageConfigName__c
                        || newUiControlRecord.XCoordinate__c != oldUiControlRecord.XCoordinate__c
                        || newUiControlRecord.YCoordinate__c != oldUiControlRecord.YCoordinate__c
                        || newUiControlRecord.Value__c!=oldUiControlRecord.Value__c
                        || newUiControlRecord.Order__c!=oldUiControlRecord.Order__c
                        || newUiControlRecord.IsHidden__c!=oldUiControlRecord.IsHidden__c
                        || newUiControlRecord.Image__c!=oldUiControlRecord.Image__c
                        || newUiControlRecord.AttachmentId__c !=oldUiControlRecord.AttachmentId__c   
                        || newUiControlRecord.Width__c != oldUiControlRecord.Width__c
                        || newUiControlRecord.Type__c != oldUiControlRecord.Type__c
                        || newUiControlRecord.IsDefault__c != oldUiControlRecord.IsDefault__c
                        || newUiControlRecord.FieldName__c != oldUiControlRecord.FieldName__c
                        || newUiControlRecord.FieldType__c != oldUiControlRecord.FieldType__c
                        || newUiControlRecord.Height__c != oldUiControlRecord.Height__c

                        ))
                )
            {
                PageConfigNameIds.add(newUiControlRecord.PageConfigName__c);
            }
        }

        List<PageConfig__c> listPageConfig = [SELECT Id, AppSetting__c 
                                              FROM PageConfig__c 
                                              WHERE id IN: PageConfigNameIds];
                                              
        List<AppSettings__c> appSettingsToUpdate = new List<AppSettings__c>();
        Set<Id> appSettingIds = new Set<Id>();
               
        // capture all the appSettings  to be updated
        for(PageConfig__c currentPageConfig : listPageConfig)
        {
            appSettingIds.add(currentPageConfig.AppSetting__c);
        }
        // update the hash key and put it in list for updating
        for(Id currentAppSettingId : appSettingIds)
        {
            String hashKey = UCB_Utility.generateRandomHashKey();
            appSettingsToUpdate.add(new AppSettings__c(Id = currentAppSettingId, Hash_Key__c = hashKey));
        }
        // update AppSettings data
        update appSettingsToUpdate;
    }

    public static void populateHashKeyOnDelete( List<UIControl__c> listUiControl)
    {

        List<AppSettings__c> appSettingsToUpdate = new List<AppSettings__c>();
        List<PageConfig__c> pageConfigs = new List<PageConfig__c>();

        List<PageConfig__c> listPageConfigs=[SELECT Id,AppSetting__c 
                                             FROM PageConfig__c
                                             LIMIT 50000 ];

        for(UIControl__c myUiControl : listUiControl)
        {
            for(PageConfig__c myPageConfig :listPageConfigs)
            {
                if(myPageConfig.Id == myUiControl.PageConfigName__c)
                {
                    pageConfigs.add(myPageConfig);
                    break;
                }
            }            
        }
        // update the hash key and put it in list for updating     
        for(PageConfig__c myFinalPageConfig : pageConfigs)
        {
            String hashKey = UCB_Utility.generateRandomHashKey();
            appSettingsToUpdate.add(new AppSettings__c(Id = myFinalPageConfig.AppSetting__c, Hash_Key__c = hashKey));
        }       
        // update AppSettings data
        update appSettingsToUpdate;
    }        
}