src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>AppVersion__c</fullName>
        <label>AppVersion</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HistoryUserKeyGenerated__c.object
<CustomObject>
    <label>HistoryUserKeyGenerated</label>
    <nameField>
        <label>HistoryUserKeyGenerated Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HistoryUserKeyGenerateds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Key__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Key</label>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>height__c</fullName>
        <label>height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>width__c</fullName>
        <label>width</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCtrGenerateKeyForUSer.cls
/*
@Company        :Your SL
@Author         :Jyothi M
@Creation date  :16/06/2015
@Reference      :
*/

@IsTest
private class TestCtrGenerateKeyForUSer {
	
	static testmethod void generateKeyForUSer () {
		Profile p=[SELECT id
				   FROM Profile
				   WHERE Name='Standard User'];
		User u=new User(UserName='jyothi.m@neradevelopment.or',Alias='jmora', Email='jyothi.m@neradevelopment.org',EmailEncodingKey='ISO-8859-1',LastName='Moravapalli',LanguageLocaleKey='de',
		ProfileId=p.Id,TimeZoneSidKey='Europe/Berlin', LocaleSidKey='de');
		insert u;
		 MobileDevice__c objmobileDevice = new MobileDevice__c(Name = 'Samsung', height__c = 7, width__c = 5);
        insert objmobileDevice;
        AppSettings__c objAppSettings = new AppSettings__c(AppVersion__c = 1.5, Name = 'IPadAir2', mobileDevice__c = objmobileDevice.id);
        insert objAppSettings;
		HistoryUserKeyGenerated__c objHistoryUserKeyGenerated=new HistoryUserKeyGenerated__c(Name='NERA');
		insert objHistoryUserKeyGenerated;
		key__c objkey=new key__c(Name ='neradevelopment');
		insert objkey;
			CtrGenerateKeyForUSer Ctr=new CtrGenerateKeyForUSer();
			ctr.generateKeyForUser();
			ctr.sendUserKey();
			System.assertEquals(1,1);
	}
	
	 
}