src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>AppVersion__c</fullName>
        <label>AppVersion</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hash_Key__c</fullName>
        <label>Hash Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <description>the semantic version for the app</description>
        <label>version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>height__c</fullName>
        <label>height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>width__c</fullName>
        <label>width</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PageConfigName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageConfig</label>
        <referenceTo>PageConfig__c</referenceTo>
        <relationshipLabel>UIControls</relationshipLabel>
        <relationshipName>UIControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CtrAppSettingConfig.cls
/*
 @Company: Mold tek India  
 @Author: Sunny  
 @Creation date: 20/05/2015
 @Ref: Create dashboard for editing app settings
*/
Public class CtrAppSettingConfig {

    

 Public List<PageConfig__c> pageConfiglist{get; set;}
 Public List<UIControl__c> uiControllerslist{get; set;}
 Public List<AppSettings__c> appSettingslist{get; set;}
 Public List<UIControl__c> uiControllerslist1 { get; set;}
 Public List<SelectOption> listPage {get; set;}
 Public String pageConfigselect{get; set;}
 Public String selectedAppSettings{get; set;}
 Public String selectedUIControllers{get; set;}
 Public String appSettingValue {get; set;}
 Public String pageConfigValue {get; set;}
 Public AppSettings__c appSett {get; set;}
 
 

        Public Map <String,AppSettings__c> mapStringAppsttings = new Map <String,AppSettings__c>();
        Public Map <String,PageConfig__c> mapStringPageConfig = new Map <String,PageConfig__c>();
    
        Public CtrAppSettingConfig()
        {
        appsett = new AppSettings__c();
        appSettingslist = new List<AppSettings__c>();

            For(AppSettings__c app:[Select id,name,(select id,name from PageConfigs__r) From AppSettings__c])
            {
            appSettingslist.add(app);
            mapStringAppsttings.Put(app.ID,app);
            }
 
        }
        
        Public void PageUIcon() {
        
        uiControllerslist1 =null; 
   
        pageConfiglist = new List<PageConfig__c>();
           if(pageConfigselect!='none')
            {
                for(PageConfig__c pagCon:[select id,name,(select name,Height__c,Width__c,XCoordinate__c,YCoordinate__c from UIControls__r) from PageConfig__c where id=:PageConfigselect])
                {
                pageConfiglist.add(pagCon);
                mapStringPageConfig.Put(pagCon.ID,pagCon);            
                }
             
            String pageJSON = JSON.serializePretty(pageConfiglist);
            System.debug(pageJSON);
        uiControllerslist = new list<UIControl__c>();
        uiControllerslist = mapStringPageConfig.Get(pageConfigselect).UIControls__r;
        
        
         }

        }
    
        Public List<SelectOption> GetPageConfig() { 
            
        return listpage;
        
        } 
        
        
        Public void GetAppSettings() {
           
        uiControllerslist =null;
        uiControllerslist1 =null;
          
        appsettingvalue = mapStringAppsttings.Get(selectedAppSettings).name;
          
        pageConfiglist = new List<PageConfig__c>();               
        pageConfiglist = mapStringAppsttings.Get(selectedAppSettings).PageConfigs__r;

            listpage = new List<SelectOption>();

            listpage.add(new SelectOption('None','None'));              
            for(PageConfig__c pa: pageConfiglist){   

            listpage.add(new SelectOption(pa.id,pa.name));                              
            } 
        }
        
        Public void GetUIControllers( ) {

           uiControllerslist1 = new List<UIControl__c>();   

            for(UIControl__c uicon:[select id,name,Height__c,Width__c,XCoordinate__c,YCoordinate__c from UIControl__c where id=:selecteduicontrollers])
            {
            uiControllerslist1.add(uicon);           
            }   
      
                  
        }
        
           
        Public PageReference Cancelit() {
        return null;
        }
        
        
        Public PageReference SaveAppSettings() {
        
        AppSettings__c aset = new AppSettings__c();
        aset.Name = appsett.Name;
        aset.AppVersion__c = appsett.AppVersion__c;
        aset.Hash_Key__c = appsett.Hash_Key__c;
        aset.mobileDevice__c = appsett.mobileDevice__c;
        aset.version__c = appsett.version__c;
        
        try {
            Insert aset;
        } catch (Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        PageReference pagref = new PageReference('/apex/AppSettingConfigpage');
        pagref.setredirect(false);
        return pagref ;
        
        
        
        }
   Public Class JSONClass {

    public String id;
    public String Height1;
    public String Width1;
    public String XCoordinate1;
    public String YCoordinate1;

}
   
    
    @RemoteAction
    public static void GetUIControl(String jsondata)
     {
        // system.debug('@@@ Json data== '+jsondata);
         list<JSONClass> lstJSONClass = new list<JSONClass>();
         JSONParser parser = JSON.createParser(jsondata);        
         while (parser.nextToken() != null) {        
        if (parser.getCurrentToken() == JSONToken.START_ARRAY) {
            while (parser.nextToken() != null) {
                
                if (parser.getCurrentToken() == JSONToken.START_OBJECT) {
                                        
                    JSONClass jsoncls = (JSONClass)parser.readValueAs(JSONClass.class);
                    lstJSONClass.add(jsoncls);
                    
                 //   system.debug('@@@ inv value== '+jsoncls);
                  //  String s = JSON.serialize(jsoncls);
                  //  system.debug('Serialized JSONClass: ' + s);

                    parser.skipChildren();
                }
            }
        }
    }
    
    system.debug('@@@@ lst json records== '+lstJSONClass);

         list<UIControl__c> lstUIcontrols = new list<UIControl__c>();

         Map<string,UIControl__c> mapStringUIControl = new  map<string,UIControl__c>();
         for(JSONClass rec : lstJSONClass){
             UIControl__c Uicon = new UIControl__c();
             uicon.id = rec.id;
             uicon.Height__c = decimal.valueof(rec.Height1);
             uicon.Width__c = decimal.valueof(rec.Width1);
             uicon.XCoordinate__c = decimal.valueof(rec.XCoordinate1);
             uicon.YCoordinate__c = decimal.valueof(rec.YCoordinate1);
             //if(!mapUiControls.containskey(Uicon.id))
             mapStringUIControl.put(Uicon.id,Uicon);
             system.debug('@@@@ map value=='+mapStringUIControl);
             //lstUIcontrols.add(Uicon);
         }
         
         if(!mapStringUIControl.values().isempty())
             update mapStringUIControl.values();

    

  
}
    
      


}