src/objects/AppSettings__c.object
<CustomObject>
    <description>this holds the information about the setting for a specific app</description>
    <fields>
        <fullName>AppVersion__c</fullName>
        <label>AppVersion</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>mobileDevice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MobileDevice</label>
        <referenceTo>MobileDevice__c</referenceTo>
        <relationshipLabel>AppSetting</relationshipLabel>
        <relationshipName>AppSetting</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AppSetting</label>
    <nameField>
        <label>AppSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>attachmentId__c</fullName>
        <label>attachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>height__c</fullName>
        <label>height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>width__c</fullName>
        <label>width</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PageConfig__c.object
<CustomObject>
    <description>this holds information about various Page configs for a specific AppSettings</description>
    <fields>
        <fullName>AppSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AppSetting</label>
        <referenceTo>AppSettings__c</referenceTo>
        <relationshipLabel>PageConfigs</relationshipLabel>
        <relationshipName>PageConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PageConfig</label>
    <nameField>
        <label>PageConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestEctrPageConfigcPhotoUpload.cls
/*
@Company        :Your SL
@Author         :Jyothi M
@Creation date  :12/06/2015
@Reference      :
*/
@isTest
private class TestEctrPageConfigcPhotoUpload{

    //This method checks whether  one record inserted in to the Attachment object or not
    //And checks whether Attachment field in Pageconfig object updated with AttachmentId or not 
    static testmethod void pageConfigPhotoUpload(){

        TestDataUtility.createNeraTriggerCustomSetting();
        
        MobileDevice__c objMobileDevice = new MobileDevice__c(Name = 'IPadAir2', height__c = 1.5, width__c = 1.2);
        insert objMobileDevice;
        AppSettings__c objAppSettings = new AppSettings__c(Name = 'IPadAir2', mobileDevice__c = objMobileDevice.Id, AppVersion__c = 123.0);
        insert objAppSettings;
        PageConfig__c objPageConfig = new PageConfig__c(Name = 'LoginPage', AppSetting__c = objAppSettings.Id);
        insert objPageConfig;
        Attachment attach = new Attachment(Name = 'icon_login.svg', ParentId = objPageConfig.Id, Body = blob.valueOf('Test attachment body'));
        insert attach;

        objPageConfig.AttachmentId__c = attach.Id;
        update objPageConfig;

        PageReference p = Page.MobileDevices;
        Test.setCurrentPage(p);
        ApexPages.currentPage().getParameters().put('id', objPageConfig.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(objPageConfig);
        EctrPageConfigcPhotoUpload objEctrPageConfigcPhotoUpload = new EctrPageConfigcPhotoUpload(sc);
        objEctrPageConfigcPhotoUpload.uploadPicFile = attach.body;
        objEctrPageConfigcPhotoUpload.attachfilename = attach.Name;
        objEctrPageConfigcPhotoUpload.toggle();
        objEctrPageConfigcPhotoUpload.saveFile();
       system.assertEquals(attach.Id, objPageConfig.AttachmentId__c);
    }

//This Method for covering catch part
    static testmethod void pageConfigPhotoUploadCatch(){

        TestDataUtility.createNeraTriggerCustomSetting();
        
        MobileDevice__c objMobileDevice = new MobileDevice__c(Name = 'IPadAir2', height__c = 1.5, width__c = 1.2);
        insert objMobileDevice;
        AppSettings__c objAppSettings = new AppSettings__c(Name = 'IPadAir2', mobileDevice__c = objMobileDevice.Id, AppVersion__c = 123.0);
        insert objAppSettings;
        PageConfig__c objPageConfig = new PageConfig__c(Name = 'LoginPage', AppSetting__c = objAppSettings.Id);
        insert objPageConfig;
        Attachment attach = new Attachment(Name = 'icon_login.svg', ParentId = objPageConfig.Id, Body = blob.valueOf('Test attachment body'));
        insert attach;

        //objPageConfig.AttachmentId__c = attach.Id;
        update objPageConfig;

        ApexPages.StandardController sc = new ApexPages.StandardController(objPageConfig);
        EctrPageConfigcPhotoUpload objEctrPageConfigcPhotoUpload = new EctrPageConfigcPhotoUpload(sc);
        objEctrPageConfigcPhotoUpload.uploadPicFile = attach.body;
        objEctrPageConfigcPhotoUpload.saveFile();
        system.assertNotEquals(attach.Id, objPageConfig.AttachmentId__c);
    }

}