src/objects/ConsumerProductStockStatus__c.object
<CustomObject>
    <fields>
        <fullName>Potential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Potential</label>
        <type>Checkbox</type>
    </fields>
    <label>ConsumerProductStockStatus</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ConsumerProductStockStatuss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential__c.object
<CustomObject>
    <label>Potential</label>
    <nameField>
        <label>Potential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WsConsumerProductStockStatus.cls
/*
@Company:Your SL
@Author:veera
@Creation date:28/7/2015
Reference: Ticket no 
*/

@RestResource(urlMapping = '/ConsumerProductStockStatus/*')


global class WsConsumerProductStockStatus implements WsPos
{
public static WsPosResponse  doReply(WsPosRequest request) {
        return new WsPosResponse ();
    }
    @HttpGet
    global static void wsGet() {
    
    WsPosRequest myRequest = new WsPosRequest(RestContext.request);
    List<ConsumerProductStockStatus__c> listDataset = getConsumerProductStockStatus();
     RestContext.response.responseBody = Blob.valueOf(JSON.serialize(listDataset));
    RestContext.response.addHeader('Content-Type', 'application/json');
}

public static List<ConsumerProductStockStatus__c> getConsumerProductStockStatus()
{
List<ConsumerProductStockStatus__c> lstConsumerProductStockStatus =[Select id, Name, Potential__c From ConsumerProductStockStatus__c ];

return lstConsumerProductStockStatus;
}

}