src/objects/MobileDevice__c.object
<CustomObject>
    <description>this is the template for the devices</description>
    <fields>
        <fullName>height__c</fullName>
        <label>height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>width__c</fullName>
        <label>width</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>MobileDevice</label>
    <nameField>
        <label>MobileDevice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MobileDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestWsAttachments.cls
/*
@Company        :Your SL
@Author         :Jyothi
@Creation date  :11/08/2015
@Reference      :
*/
@isTest
private class TestWsAttachments {

    static testMethod void doGet(){
        TestDataUtility.createNeraTriggerCustomSetting();
        MobileDevice__c objMobileDevice=new MobileDevice__c(Name='IPadAir2',height__c =768.0,width__c=1024.0);
        insert objMobileDevice;
        List<Attachment> listAttachment=new List<Attachment>();
        listAttachment.add(new Attachment(Name='checked.svg',Body=Blob.valueof('Attachmentbody'),ParentId=objMobileDevice.Id));
        listAttachment.add(new Attachment(Name='icon_login.svg',Body=Blob.valueof('New Attachmentbody'),ParentId=objMobileDevice.Id));
        listAttachment.add(new Attachment(Name='new_logo.svg',Body=Blob.valueof('Attachmentbody1'),ParentId=objMobileDevice.Id));
        insert listAttachment;
        List<String> imageIds = new List<String>();
        for(Attachment lstAttachment:listAttachment){
            imageIds.add(lstAttachment.Id);
        }

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = 'https://eu5.salesforce.com/services/apexrest/Attachments';
        req.httpMethod = 'GET';
        req.addParameter('ImageIds',JSON.Serialize(imageIds));
        RestContext.request = req;
        RestContext.response = res;
        UcbWsRequest myRequest = new UcbWsRequest(RestContext.request);
        WsAttachments.returnImages();
        WsAttachments.doReply(myRequest);
        system.debug('RestContext.response----------'+JSON.serialize(RestContext.response));
        //system.assertEquals(JSON.serialize(RestContext.response.statusCode),null);
        system.assertNotEquals(EncodingUtil.base64Encode(listAttachment[0].Body),JSON.serialize(RestContext.response.responseBody));
    }
    
}