src/objects/Organization__c.object
<CustomObject>
    <fields>
        <fullName>ParentOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ParentOrganization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Organizations</relationshipLabel>
        <relationshipName>Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CtrParentOrganization.cls
public class CtrParentOrganization {
    //public List<Organization__c> listOrg{get;set;}
    public CtrParentOrganization(ApexPages.StandardController controller) {
        //String orgId = apexpages.currentpage().getparameters().get('id'); 
        //listOrg = [SELECT ParentOrganization__c,ParentOrganization__r.Name FROM Organization__c WHERE id=:orgiId];  
    }

    public void deleteRecord(){
    	
    }
}