src/objects/Organization__c.object
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrganizationAccountMember__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OrganizationAccountMembers</relationshipLabel>
        <relationshipName>OrganizationAccountMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>OrganizationAccountMembers</relationshipLabel>
        <relationshipName>OrganizationAccountMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OrganizationAccountMember</label>
    <nameField>
        <label>OrganizationAccountMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrganizationAccountMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EctrAccountRelatedOrganization.cls
public with sharing class EctrAccountRelatedOrganization {
    public List<Organization__c> listorg {get; set;}
    public String orgId {get; set;}
    public EctrAccountRelatedOrganization (ApexPages.StandardController controller) {
        orgId = apexpages.currentpage().getparameters().get('id');
        organizationData(orgId);
    }
    public void organizationData(String orgId) {
        listorg = new List<Organization__c>();
        for (OrganizationAccountMember__c orgmember : [SELECT Account__c, Organization__r.Name, Organization__r.OwnerId,  Organization__c
                FROM OrganizationAccountMember__c WHERE Account__c = :orgId]) {
            Organization__c org = new Organization__c();
            org.Id = orgmember.Organization__c ;

            org.Name = orgmember.Organization__r.Name;
            org.OwnerId = orgmember.Organization__r.OwnerId;
            listorg.add(org);
        }

    }
}