src/objects/OrganizationPriceBookMember__c.object
<CustomObject>
    <description>this is a junction object between organization and pricebook</description>
    <fields>
        <fullName>OrganizationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>OrganizationPriceBookMembers</relationshipLabel>
        <relationshipName>OrganizationPriceBookMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriceBookId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>OrganizationPriceBookMembers</relationshipLabel>
        <relationshipName>OrganizationPriceBookMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OrganizationPriceBookMember</label>
    <nameField>
        <displayFormat>opm-{000000000}</displayFormat>
        <label>OrganizationPriceBookMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrganizationPriceBookMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WsOrganizationPriceBookMember.cls
/*
@Company:Your SL
@Author:Pavan
@Creation date:
@Reference: 
*/
@RestResource(urlMapping = '/OrganizationPriceBookMember/*')
global class WsOrganizationPriceBookMember implements UcbWs {

    public static UcbWsResponse doReply(UcbWsRequest request) {
        return new UcbWsResponse();
    }

    @HttpGet
    global static void wsGet() {
        //Create Request
        UcbWsRequest myRequest = new UcbWsRequest(RestContext.request);
        List<OrganizationPriceBookWrapper> listOrgWrapper = organizationPriceBooks();
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(listOrgWrapper));
        RestContext.response.addHeader('size', String.valueOf(listOrgWrapper.Size()));
        RestContext.response.addHeader('Content-Type', 'application/json');

    }
    public static List<OrganizationPriceBookWrapper> organizationPriceBooks(){
        List<OrganizationPriceBookMember__c> listOrganizationMembers = [SELECT Name,
                                                                               PriceBookId__c,
                                                                               LastModifiedDate,
                                                                               CreatedDate,
                                                                               OrganizationId__c
                                                                        FROM OrganizationPriceBookMember__c
                                                                        LIMIT 50000];
        List<OrganizationPriceBookWrapper> listOrganizations = new List<OrganizationPriceBookWrapper>();
        for(OrganizationPriceBookMember__c myMember : listOrganizationMembers){
            OrganizationPriceBookWrapper orgMember = new OrganizationPriceBookWrapper(myMember);
            listOrganizations.add(orgMember);
        }
        return listOrganizations;
    }

    public class OrganizationPriceBookWrapper{
        public String organizationPromotionMemberId;
        public String name{get; set;}
        public String organizationId{get; set;}
        public String priceBookId{get; set;}
        public Datetime lastModifiedDate;
        public Datetime createdDate;
    
        public OrganizationPriceBookWrapper(OrganizationPriceBookMember__c myOrgmember){
            this.name = myOrgmember.Name;
            this.organizationId = myOrgmember.OrganizationId__c;
            this.priceBookId = myOrgmember.PriceBookId__c;
            this.organizationPromotionMemberId = myOrgmember.Id;
            this.lastModifiedDate = myOrgmember.LastModifiedDate;
            this.createdDate = myOrgmember.CreatedDate;
        }
    }    
}