src/objects/POIDevice__c.object
<CustomObject>
    <fields>
        <fullName>POIDeviceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POIDeviceType</label>
        <referenceTo>POIDeviceType__c</referenceTo>
        <relationshipLabel>POIDevices</relationshipLabel>
        <relationshipName>POIDevices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>POIDevice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POIDevices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/POIDeviceType__c.object
<CustomObject>
    <label>POIDeviceType</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POIDeviceTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Wspoidevice.cls
/*
@Company:Your SL
@Author:veera
@Creation date:28/7/2015
Reference: Ticket no 
*/

@RestResource(urlmapping = '/PoiDeviceType/*')

global class Wspoidevice implements WsPos {

    public static WsPosResponse doReply(WsPosRequest request) {
        return new WsPosResponse();

    }

    @HttpGet

    global static PoiDeviceType wsDeviceGet() {
        try {

            List < POIDeviceType__c > listPoiDevicetype = [SELECT Id, Name, (select id,Name,POIDeviceType__c From POIDevices__r) FROM POIDeviceType__c];

            
            return new PoiDeviceType('true', 'Query Executed Successfully.', listPoiDevicetype);
            
        } catch (Exception e) {


            return new PoiDeviceType('false', e.getMessage(), null);
        }
    }

    Global class PoiDeviceType {
        public String success {get;set;}
        public String message{get;set;} 
        public List < POIDeviceType__c > poiDevicetypevalue {get;set;}
            
    global PoiDeviceType(String success, String message, List < POIDeviceType__c > poiDevicetypevalue) {
            this.success = success;
            this.message = message;
            this.poiDevicetypevalue = poiDevicetypevalue;
        }

    }
}