src/objects/ProductGroup__c.object
<CustomObject>

    <label>ProductGroup</label>
    <nameField>
        <label>ProductGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroupMember__c.object
<CustomObject>
    <fields>
        <fullName>Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ProductGroupMembers</relationshipLabel>
        <relationshipName>ProductGroupMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProductGroup</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>ProductGroupMembers</relationshipLabel>
        <relationshipName>ProductGroupMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProductGroupMember</label>
    <nameField>
        <displayFormat>pgm-{00000000}</displayFormat>
        <label>ProductGroupMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductGroupMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WsProductGroupMembers.cls
/*
@Company:Your SL
@Author:Parasuram
@Creation date:06/08/2015
Reference:
*/

@RestResource(urlMapping = '/ProductGroupMembers/*')
global class WsProductGroupMembers implements UcbWs {

    public static UcbWsResponse doReply(UcbWsRequest request) {
        return new UcbWsResponse();
    }

    @HttpGet
    global static void wsGet() {
    	// do businesslogic
    	UcbWsRequest myRequest = new UcbWsRequest(RestContext.request);    	
    	List<ProductGroupMember> listProductGroupMember = getProductGroupMembers();
    	RestContext.response.responseBody = Blob.valueOf(JSON.serialize(listProductGroupMember));
    	RestContext.response.addHeader('size', String.valueOf(listProductGroupMember.Size()));
    	RestContext.response.addHeader('Content-Type', 'application/json');
    }

    // To get all Product group members
    public static List<ProductGroupMember> getProductGroupMembers(){
    	List<ProductGroupMember__c> listProductGroupMembers = [SELECT Name,
																	  Product2Id__c,
																	  ProductGroup__c,
                                                                      LastModifiedDate,
                                                                      CreatedDate 
    														   FROM ProductGroupMember__c
                                                               LIMIT 50000];
		List<ProductGroupMember> listProductGpMembers = new List<ProductGroupMember>();
		for(ProductGroupMember__c productGroupMember : listProductGroupMembers){
			ProductGroupMember productGpMember = new ProductGroupMember(productGroupMember);
			listProductGpMembers.add(productGpMember);
		}
    	return ListProductGpMembers;
    }

    public class ProductGroupMember{
    	public String name{get; set;}
    	public String product2Id{get; set;}
    	public String groupId{get; set;}
        public Datetime lastModifiedDate;
        public Datetime  createdDate; 
    	public ProductGroupMember(ProductGroupMember__c member){
    		this.name = member.Name;
    		this.product2Id = member.Product2Id__c;
    		this.groupId = member.ProductGroup__c;
            this.lastModifiedDate = member.LastModifiedDate;
            this.createdDate = member.CreatedDate;
    	}
    }
}