src/objects/Promotion__c.object
<CustomObject>
    <fields>
        <fullName>ActionValidityEndDate__c</fullName>
        <label>ActionValidityEndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ActionValidityStartDate__c</fullName>
        <label>ActionValidityStartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SellingValidityEndDate__c</fullName>
        <label>SellingValidityEndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SellingValidityStartDate__c</fullName>
        <label>SellingValidityStartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestWsPromotions.cls
/*
@Company        :Your SL
@Author         :Jyothi
@Creation date  :11/08/2015
@Reference      :
*/
@isTest
private class TestWsPromotions {

  static testmethod void doGet() {
    TestDataUtility.createNeraTriggerCustomSetting();
    Promotion__c objPromotion = new Promotion__c(Name = 'Promo1', StartDate__c = system.today(), EndDate__c = system.today() + 3, ActionValidityEndDate__c = system.today() + 5, ActionValidityStartDate__c = system.today() + 7,
        Description__c = 'Test displayed', SellingValidityEndDate__c = system.today() + 8, SellingValidityStartDate__c = system.today() + 10);
    insert objPromotion;
    Attachment objAttachment = new Attachment(Name = 'checked.svg', Body = Blob.valueof('Attachmentbody'), ParentId = objPromotion .Id);
    insert  objAttachment;

    objPromotion.AttachmentId__c = objAttachment.Id;
    update objPromotion;

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = 'https://eu5.salesforce.com/services/apexrest/Promotions';
    req.httpMethod = 'GET';
    RestContext.request = req;
    RestContext.response = res;

    UcbWsRequest myRequest = new UcbWsRequest(RestContext.request);
    WsPromotions.wsGet();
    WsPromotions.doReply(myRequest);

  }
}