src/objects/Talon__c.object
<CustomObject>
    <label>Talon</label>
    <nameField>
        <label>Talon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TalonPriceBookEntryMember__c.object
<CustomObject>
    <fields>
        <fullName>PriceBookEntryId__c</fullName>
        <label>PriceBookEntryId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Talon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Talon</label>
        <referenceTo>Talon__c</referenceTo>
        <relationshipName>TalonPriceBookEntryMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TalonPriceBookEntryMember</label>
    <nameField>
        <displayFormat>tpm-{0000000}</displayFormat>
        <label>TalonPriceBookEntryMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TalonPriceBookEntryMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WsTalonPriceBookEntryMember.cls
/*
@Company:Your SL
@Author:Pavan
@Creation date:9/3/2015
@Reference: ticket no:1114
*/
@RestResource(urlMapping = '/TalonPriceBookEntryMember/*')
global class WsTalonPriceBookEntryMember implements UcbWs {

    public static UcbWsResponse doReply(UcbWsRequest request) {
        return new UcbWsResponse();
    }

    @HttpGet
    global static void wsGet() {
    	//create request
    	UcbWsRequest myrequest = new UcbWsRequest(RestContext.request);
    	List<TalonPriceBookentryWrapper> listTalonWrapper = getTalonPriceBookentries();
    	RestContext.response.responseBody = Blob.valueOf(JSON.serialize(listTalonWrapper));
    	RestContext.response.addHeader('size', String.valueOf(listTalonWrapper.Size()));
    	RestContext.response.addHeader('Content-Type', 'application/json');
    }
    public static List<TalonPriceBookentryWrapper> getTalonPriceBookentries(){
    	List<TalonPriceBookEntryMember__c> listTalonPriceBooks =[SELECT Id,Name,Talon__c,
    																	PriceBookEntryId__c,
    																	LastModifiedDate,
                                                                        CreatedDate
    															 FROM TalonPriceBookEntryMember__c
                                                                 LIMIT 50000];
    	List<TalonPriceBookentryWrapper> listTalonWrapper = new List<TalonPriceBookentryWrapper>();
    	for(TalonPriceBookEntryMember__c myTalons:listTalonPriceBooks){
    		TalonPriceBookentryWrapper talonpriceBook = new TalonPriceBookentryWrapper(myTalons);
    		listTalonWrapper.add(talonpriceBook);
    	}
    	return listTalonWrapper;
    }
   public class TalonPriceBookentryWrapper{
		public String talonPriceBookEntryId;
		public String priceBookEntryId;
		public String talonId;
		public String name;
		public Datetime lastModifiedDate;
		public Datetime createdDate;
		public TalonPriceBookentryWrapper(TalonPriceBookEntryMember__c myTalonPriceBook){
			this.talonPriceBookEntryId = myTalonPriceBook.Id;
			this.name = myTalonPriceBook.Name;
			this.talonId = myTalonPriceBook.Talon__c;
			this.priceBookEntryId = myTalonPriceBook.PriceBookEntryId__c;
			this.lastModifiedDate = myTalonPriceBook.LastModifiedDate;
			this.createdDate = myTalonPriceBook.CreatedDate;
		}
	}	
}