src/objects/UIControl__c.object
<CustomObject>
    <description>this holds information about dimensions of various UI Controls for a specific page</description>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XCoordinate__c</fullName>
        <label>XCoordinate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YCoordinate__c</fullName>
        <label>YCoordinate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>UIControl</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UIcontrollercls.cls
public class UIcontrollercls {
	public Integer height {get; set;}
	public Integer width {get; set;}
	public Integer xCoordinate {get; set;}
	public Integer yCoordinate {get; set;}


	Public UIcontrollercls () {
		List <UIControl__c>   ui = [SELECT id, Name, Height__c, Width__c, XCoordinate__c, YCoordinate__c
		                            FROM UIControl__c
		                            LIMIT 50000];


		string str = JSON.serialize(ui);
		system.debug('.....line15......' + str);
	}
	UIcontrollercls  uiCla = new UIcontrollercls  ();
	string str1 = JSON.serialize(uiCla);

	UIcontrollercls  gCalendarDeserialized = (UIcontrollercls) JSON.deserialize(str1, UIcontrollercls .class);
}