src/objects/VisitScorePotential__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VisitScorePotentialGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VisitScorePotentialGroup</label>
        <referenceTo>VisitScorePotentialGroup__c</referenceTo>
        <relationshipLabel>VisitScorePotentials</relationshipLabel>
        <relationshipName>VisitScorePotentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VisitScorePotential</label>
    <nameField>
        <label>VisitScorePotential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VisitScorePotentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VisitScorePotentialGroup__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>VisitScorePotentialGroup</label>
    <nameField>
        <label>VisitScorePotentialGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VisitScorePotentialGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VisitScoreResult__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>VisitScoreResults</relationshipLabel>
        <relationshipName>VisitScoreResults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>VisitScoreResult</label>
    <nameField>
        <displayFormat>rs-{000000000}</displayFormat>
        <label>VisitScoreResult Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VisitScoreResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VisitScoreResultPotential__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VisitScorePotential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VisitScorePotential</label>
        <referenceTo>VisitScorePotential__c</referenceTo>
        <relationshipLabel>VisitScoreResultPotentials</relationshipLabel>
        <relationshipName>VisitScoreResultPotentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VisitScoreResult__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VisitScoreResult</label>
        <referenceTo>VisitScoreResult__c</referenceTo>
        <relationshipLabel>VisitScoreResultPotentials</relationshipLabel>
        <relationshipName>VisitScoreResultPotentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VisitScoreResultPotential</label>
    <nameField>
        <displayFormat>rsrp-{000000000}</displayFormat>
        <label>VisitScoreResultPotential Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VisitScoreResultPotentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VisitScoreResultType__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResultInPercentage__c</fullName>
        <label>ResultInPercentage</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>VisitScoreResult__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VisitScoreResult</label>
        <referenceTo>VisitScoreResult__c</referenceTo>
        <relationshipLabel>VisitScoreResultTypes</relationshipLabel>
        <relationshipName>VisitScoreResultTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VisitScoreType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VisitScoreType</label>
        <referenceTo>VisitScoreType__c</referenceTo>
        <relationshipLabel>VisitScoreResultTypes</relationshipLabel>
        <relationshipName>VisitScoreResultTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VisitScoreResultType</label>
    <nameField>
        <displayFormat>rsrt-{00000000}</displayFormat>
        <label>VisitScoreResultType Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VisitScoreResultTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VisitScoreType__c.object
<CustomObject>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>VisitScoreType</label>
    <nameField>
        <label>VisitScoreType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VisitScoreTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestWsVisitScore.cls
/*
@Company        :Your SL
@Author         :Imran
@Creation date  :07/08/2015
@Reference      :
*/
@isTest
global class TestWsVisitScore {
  
  static testMethod void testWsVisitScore() {

    Test.startTest();
      CleanUpTestData.createNeraTriggerCustomSetting();
      
      List<Account> listAccount = new List<Account>();
        listAccount.add(new Account(Name='United Gas'));
        listAccount.add(new Account(Name='Yoursl'));
      insert listAccount;

      List<VisitScoreResult__c> listVisitScoreResult = new List<VisitScoreResult__c>();
        listVisitScoreResult.add(new VisitScoreResult__c(Account__c=listAccount[0].ID,Result__c=20,Date__c=Date.today()));
        listVisitScoreResult.add(new VisitScoreResult__c(Account__c=listAccount[1].ID,Result__c=20,Date__c=Date.today()));
      insert listVisitScoreResult;

      List<VisitScoreType__c> listVisitScoreType = new List<VisitScoreType__c>();
        listVisitScoreType.add(new VisitScoreType__c(IsDefault__c=true,Order__c=2));
        listVisitScoreType.add(new VisitScoreType__c(IsDefault__c=true,Order__c=4));
      insert listVisitScoreType;


      List<VisitScoreResultType__c> listVisitScoreResultType = new List<VisitScoreResultType__c>();
        listVisitScoreResultType.add(new VisitScoreResultType__c(VisitScoreResult__c=listVisitScoreResult[0].Id,VisitScoreType__c=listVisitScoreType[0].Id,ResultInPercentage__c=25));
        listVisitScoreResultType.add(new VisitScoreResultType__c(VisitScoreResult__c=listVisitScoreResult[1].Id,VisitScoreType__c=listVisitScoreType[1].Id,ResultInPercentage__c=50));
      insert listVisitScoreResultType;

      List<VisitScorePotentialGroup__c> listVisitScorePotentialGroup = new List<VisitScorePotentialGroup__c>();
        listVisitScorePotentialGroup.add(new VisitScorePotentialGroup__c(IsDefault__c=true,Order__c=2));
        listVisitScorePotentialGroup.add(new VisitScorePotentialGroup__c(IsDefault__c=true,Order__c=4));
      insert listVisitScorePotentialGroup;

      List<VisitScorePotential__c> listVisitScorePotential = new List<VisitScorePotential__c>();
        listVisitScorePotential.add(new VisitScorePotential__c(IsDefault__c=true,Order__c=3,VisitScorePotentialGroup__c=listVisitScorePotentialGroup[0].Id));
        listVisitScorePotential.add(new VisitScorePotential__c(IsDefault__c=true,Order__c=5,VisitScorePotentialGroup__c=listVisitScorePotentialGroup[1].Id));
      insert listVisitScorePotential;

      List<VisitScoreResultPotential__c> listisitScoreResultPotential = new List<VisitScoreResultPotential__c>();
        listisitScoreResultPotential.add(new VisitScoreResultPotential__c(IsDefault__c=true,VisitScorePotential__c=listVisitScorePotential[0].Id,VisitScoreResult__c=listVisitScoreResult[0].Id));
        listisitScoreResultPotential.add(new VisitScoreResultPotential__c(IsDefault__c=true,VisitScorePotential__c=listVisitScorePotential[1].Id,VisitScoreResult__c=listVisitScoreResult[1].Id));
      insert listisitScoreResultPotential;

      List<WsVisitScore.MyAccount> listAccountWrapper = new List<WsVisitScore.MyAccount>();
        WsVisitScore.MyAccount myAccountWrapper = new WsVisitScore.MyAccount();
          myAccountWrapper.id = listAccount[0].Id;
      listAccountWrapper.add(myAccountWrapper);

    Test.stopTest();

    Set<String> setAcccountId = new Set<String>();
      setAcccountId.add(listAccount[0].Id);
      setAcccountId.add(listAccount[1].Id);

    RestRequest req = new RestRequest();
        req.requestURI = 'https://eu5.salesforce.com/services/apexrest/BusinessProcess';
        req.httpMethod = 'GET';
        req.addParameter('accounts', JSON.serialize(setAcccountId));
    RestResponse res = new RestResponse();

    RestContext.request = req;
      RestContext.response = res;

      UcbWsRequest myRequest = new UcbWsRequest(RestContext.request);
      WsVisitScore.doReply(myRequest);
       WsVisitScore.wsGet();

    List<WsVisitScore.MyAccount> result = WsVisitScore.deserializeMyEventRequest(JSON.serialize(listAccount));
    //system.assertEquals(result,listAccountWrapper);

  }
  
}